### ISSUE TITLE
Core Input Remapping not available in Retroarch GUI

### ISSUE THREAD

**Issue by dankcushions** [libretro/mame2003-libretro#10]
Hi,

Core Input Remapping is required as it seems the control layouts for some games don't translate correctly to the RetroPad defaults. Eg, in street fighter 2, I'd want to use the SNES layout:
Y=Light Punch
X=med Punch
L=Heavy Punch
B=Light kick
A=med kick
R=Heavy Kick
But even if my pad is configured correctly as a retropad, SF2.zip registers:
B=Light Punch
Y=Med Punch
X=Heavy Punch
A=Light Kick
L=Med Kick
R=Heavy Kick
I could reconfigure these, but that would mean that in the RGUI, A is no longer confirm, B is no longer back, etc.

I'm told that Core Input Remapping should be available in the RGUI quick menu, which would allow me to ensure my RGUI controls are correct, even if I reconfigure my inputs, but this option is not there. Apparently this option is absent when cores do not implement input descriptors? See https://github.com/libretro/fba-libretro/issues/48

So ideally this core would implement these descriptors and then I think I could reconfigure everything :) Cheers!

**Comment by dankcushions** [comment]
https://github.com/dankcushions/mame2003-libretro/commit/9cf717ff76c64711cebedbbf303f89adad309187 allows you to work around this using the internal Mame UI even if you don't have the right directory structure in place, but proper core input remapping should still be implemented.

I tried to do it but even after implementing standard remapping it seems like this core rebinds keys to defaults every frame in retro_run(). Not sure how to fix at the mo.

**Comment by bite-your-idols** [comment]
I use the mame config menu (TAB) and edit general inputs, they work but I lost that changes everytime I exit.
I am using my own compiled retroarch 1.3.6 version in RPI2 running openelec... Can I manually put somewhere any default.cfg file to save these settings? or even better the core remapping implementation would be awesome... 
thanks in advanced.

**Comment by dankcushions** [comment]
TAB works fine for me. run it with logs in and see if it managed to create the directories it wanted? core input remapping is hard to do...

**Comment by bite-your-idols** [comment]
Looking through log I find I can workaround the issue just creating a folder in config folder named "MAME 2003" and putting inside a "MAME 2003.cfg" file with custom input binds for this core, that was what I wanted to achieve with Mame TAB Menu... but TAB menu changes still don't be saved and there is no clue in log file...

**Comment by dankcushions** [comment]
can you paste your log file? with verbose turned on and the log level at 0 (debug)?

**Comment by bite-your-idols** [comment]
now it works! I updated core from libretro nightlies and it works flawlessly, also Hiscores are working now.

**Comment by bite-your-idols** [comment]
Hola, 
Estaré fuera del estudio hasta el 9 de Abril para cualquier consulta puedes escribir a studio@onclick.es o  ramon@onclick.es.

Muchas gracias
