### ISSUE TITLE
Expose which MAME options (inc. Vector options) as Core Options?

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-libretro#102]
The original Readme file incorporated a development "todo" section. That purpose is fulfilled by github's Issue tracker now so I'm creating this Issue to support any discussion of the todo.

**Comment by hizzlekizzle** [comment]
I don't think *all* of the options can reasonably be exposed as core options, since MAME has a bajillion options, some of which don't really map to the core option format very well.

However, I think we should be able to identify some more low-hanging fruit to expose.

**Comment by markwkidd** [comment]
That seems reasonable. 

The original authors were from a more optimistic time perhaps. I have updated the title of this issue to represent today's zeitgeist.

**Comment by markwkidd** [comment]
I believe things have evolved since I posted this issue so that it's no longer as relevant to have a meta-issue for core options. Closing for now.
