### ISSUE TITLE
object file errors during concurrent building

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-libretro#103]
[According to the original Readme](https://github.com/libretro/mame2003-libretro/blob/72d985e9133d21cbd275a16eef2c3196f5d9120c/README.md), sometimes there are object file errors during concurrent building.

The Readme has this to suggest about the issue: "When using concurrent building you may get an error that it can't create certain object files, just rerun make if it happens."

Things have changed in the Makefile since then. Is this still an Issue?

**Comment by dankcushions** [comment]
if "concurrent building" means using -jx to compile with more than 1 thread, then retropie uses that by default and has no problems building this core. I think this isn't an issue.

**Comment by markwkidd** [comment]
That makes sense to me. I figure I'll leave this issue open for another day or two and then close unless someone posts with a different understanding.
