### ISSUE TITLE
Sound doesn't work in Namco Classic Collections Volume 1 & 2

### ISSUE THREAD

**Issue by dharmabumstead** [libretro/mame2003-libretro#119]
Sound doesn't work in either game in lr-mame2003 (running on a Raspberry Pi 3).

It does work under another emulator (lr-mame2010), but that release still has an issue that renders vertical games in the wrong (stretched) aspect ratio.

**Comment by markwkidd** [comment]
For future troubleshooting: this is a bug with MAME 0.78 itself.

**Comment by gamez-fan** [comment]
These games would require two things in order to have full sound in MAME78 namely
the H8/3002 CPU core and the namco C352 sound core both of which would need to 
be backported from later MAME.
