### ISSUE TITLE
regression: mcr-2 and mcr-3 driver (rampage, tron, tapper, spy hunter, etc)

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-libretro#121]
I have not been able to get rampage or rampage2 to work correctly with two different builds of MAME 2003 that are about a year apart.

However I am able to download the original mame 0.78 binary from mamedev and both titles seem totally playable. Can anyone else confirm that this is a regression or other issue?

**Comment by blinkydoos** [comment]
I've never been able to get Rampage to work on lr-mame2003. The same rom works fine on lr-mame2000 and mame4all. Would it also be related to this issue as it's also a Bally game ?

https://github.com/libretro/mame2003-libretro/issues/55

**Comment by markwkidd** [comment]
@blinkydoos It might be possible. As dancushions said in that Issue, the next step is to test those titles to see how they work in Windows with the original MAME 0.78 binary. Are you able to take that project on?

**Comment by blinkydoos** [comment]
Testing in MAME 0.78 (Windows) .....

'demoderb' works fine

**Comment by markwkidd** [comment]
@gamez-fan I love all of the backport work you are doing lately!

Is there any chance you have insight into this issue with the mcr3 driver?

**Comment by gamez-fan** [comment]
The Bally games tend to have their inputs and coins handled by the main CPU in this case a Z80
via the pia6821 device, i had a quick look over the above and the mcr3 driver and machine files
i see no diffs between MAME78 and libretro2003.

So IMHO the problem must lie elseware in the source maybe in the general input code i assume 
some of this was changed for the libretro purposes..?? it might be those changes that breaks the
inputs and coining for these games..??

**Comment by gamez-fan** [comment]
What about ir-MAME2010 do these games work using that core..??

**Comment by markwkidd** [comment]
Adding that there is a similar issue, possibly the same exact issue, affecting MCR-2 games per https://retropie.org.uk/forum/post/130043

**Comment by grant2258** [comment]
what systems are you guys testing on can you please add if its 32 bit or 64 bit. Ive been working a lot lately but ive made some progress in fixing splatter house on 64 bit. This priority need fixed up though but its a start and ts very tedious working with casting issues.  There has been updates to fix issues with the 64bit for issues with the 68k and ym2151 so please make sure the older post of games not working is still valid

**Comment by grant2258** [comment]
@twinaphex @dankcushions @markwkidd  this is where we broke miday  input https://github.com/libretro/mame2003-libretro/commit/497e5173bfbd10c1514c0e8c669c261adf02e784

**Comment by grant2258** [comment]
https://www.mikesarcade.com/cgi-bin/spies.cgi?action=url&type=info&page=MCRfaq.txt 

the input is controlled via the soundcore just for reference
