### ISSUE TITLE
Bubble Bobble 2 / Bubble Bobble Symphony sound problems

### ISSUE THREAD

**Issue by LeanderAT** [libretro/mame2003-libretro#137]
Hi! BB2/BBS works on my Snes Mini with RetroArch and the line /mame2003. However, the sound has issues, latency problems and samples cut off. Everything is slooooow!
Gameplay is also affected a bit...seems everything runs too slowly.

Any ideas?

**Comment by dankcushions** [comment]
this happens on pi3 also. it's just a cpu intensive game, i guess. many games in mame2003 will not work smoothly on these low spec ARM devices.

**Comment by LeanderAT** [comment]
Thank you for your reply! Is there anything I can do? Core settings, sound settings? The game is playable but not that enjoyable.

**Comment by dankcushions** [comment]
in core options:
- could try setting frame skip to 1
- lowering the sample rate

i don't know if these will help that much, though!

**Comment by Darknior** [comment]
@gamez-fan maybe have you an (xbox trick) solution for these games too ?

**Comment by LeanderAT** [comment]
Thanks! The default sample rate is 48khz...44,1 is stereo...why is it so high?

**Comment by LeanderAT** [comment]
PS What is the default audio latency? I thought all settings are per game...but not for the whole emulator...so I messed something up. What is the default in ms?

**Comment by dankcushions** [comment]
> The default sample rate is 48khz...44,1 is stereo...why is it so high?

because that is what mame standalone was. most devices seem to be fine with it. did lowering it improve it for you?

> PS What is the default audio latency? I thought all settings are per game...but not for the whole emulator...so I messed something up. What is the default in ms?

for retroarch support, please their forums/IRC etc.

**Comment by LeanderAT** [comment]
Thanks! No, the game runs too slowly independent of audio settings. The default is 56 ms.

**Comment by rb6502** [comment]
This game is on advanced 32-bit hardware (more powerful than Sega Saturn in some ways) and its audio board is the guts from a $2500 Ensoniq synthesizer.  It's just not going to go well on current mobile devices.

**Comment by pjft** [comment]
You can set frame skip to 5 which seemed to work reasonably well. Alternatively, if playing on a Pi, AdvanceMame runs it flawlessly.
