### ISSUE TITLE
Audio samples path

### ISSUE THREAD

**Issue by S3riousSam** [libretro/mame2003-libretro#15]
I could not find this information anywhere [yet], so I'm trying here...

Does libretro MAME 2003 handles audio samples (wave files) for arcade games that required this on MAME 0.78?

Is so, where is the default folder location the core is seeking for them?

Is there a way to configure the target folder?

**Comment by objectchris** [comment]
@joolswills did a similar change for mame2000 here - https://github.com/libretro/mame2000-libretro/pull/20 - maybe a similar hack is possible here?

**Comment by windale** [comment]
Is this still being worked on ? lr-mame2003 is probably the best MAME emulator on RetroPie (for Pi 2 and above). There are 56 games that use samples. Hoping for a simple fix to detect them in the samples folder like all other MAME emulators do.

Also (unrelated), does Hi-Score saving work ?

**Comment by twinaphex** [comment]
I'm open to any pull requests sent my way at least.

**Comment by dankcushions** [comment]
I have a fix in the works that should resolve this. Almost finished!

**Comment by windale** [comment]
The ideal result would be to detect the 'samples' folder in a folder called something like 'lr-mame2003 data'. Maybe you could also get the config and nvram folders to detect there as well. That way, there will be no folders showing up in the EmulationStation game list and the roms folder would be much tidier.

**Comment by joolswills** [comment]
it's not the job of libretro cores to work around folder structure problems with emulationstation or retropie. Better to add the ability to ES to hide folders I should think (there are patches out there)

**Comment by windale** [comment]
When I mentioned folder structure I was mostly talking about one of dankcushions latest commits that added the needed mame2003 config and nvram folders directly to the roms folder. I thought it would be a bit tidier to try and add them all to one folder.

**Comment by dankcushions** [comment]
My fix isn't bespoke like that, it's merely to make the core look in the defined Retroarch System and Save directories for the appropriate mame directories which is the standard for Mame/MESS cores in retroarch -  See http://www.libretro.com/index.php/mamemessume-cores/ for how that will work.

Note: In retropie, the Save directory is currently set as the /home/pi/RetroPie/roms/[system]/, and the system directory is /home/pi/RetroPie/BIOS/

**Comment by windale** [comment]
I'll wait until you finish the samples detection, then if I rebuild lr-mame2003 it should detect the config, nvram and samples folders in '/home/pi/RetroPie/roms/lr-mame2003' folder ? Will it also work if the roms are in the 'arcade' folder ?

**Comment by dankcushions** [comment]
@windale No, as per the link above the samples directory is classed as 'additional core content' so would be in the Retroarch system folder, which in retropie is configured as /home/pi/RetroPie/roms/BIOS/

eg /home/piRetroPie/roms/BIOS/samples/

**Comment by windale** [comment]
OK, sorry, one last post to clarify. After you've added the next commit, the samples folder will be detected in the BIOS folder (as you've shown above) and the cfg and nvram folders (previously in the roms folder) will now move to 'roms/lr-mame2003' or 'roms/arcade' depending on where we have put are roms ?

**Comment by dankcushions** [comment]
Yep :)

**Comment by windale** [comment]
Excellent, patiently waiting for your fix.

**Comment by joolswills** [comment]
the changes I made for mame2000 use a samples subfolder off the roms folder - I think both modules should behave the same so if we are to use samples they should use the same structure - so if moving to system folder, a subfolder with the core name is needed so they wouldn't collide.

**Comment by windale** [comment]
Also, slightly off-topic, if a compatible Hiscore.dat file were added to the binaries folder, it should also save hi-scores to a 'hi' folder. Maybe the pre_mame0133u1 dat would be compatible from here -

http://www.mameworld.info/highscore/hiscoredat.zip

**Comment by windale** [comment]
How's it going, any updates ?

**Comment by joolswills** [comment]
It's the weekend, it's been two days, this stuff is done in peoples own free time. be patient.

**Comment by windale** [comment]
I only asked because dankcushions said he was 'almost finished' 3 days ago. Sorry for asking.

**Comment by dankcushions** [comment]
My fix is live - see https://github.com/libretro/mame2003-libretro/pull/21

NOTE: you need a very recent version of retroarch for this (see link for specific commit)

Samples are working. For retropie, they need to be in /home/pi/RetroPie/BIOS/sample/gamename.zip

**Comment by joolswills** [comment]
Regarding sample path - I mentioned above using a subfolder with the core name so we can adjust other versions of mame to use the same behaviour (my modification for mame2000 uses a sample subfolder under the rom file) - samples are different between mame version etc so we might want to change this.

**Comment by joolswills** [comment]
(it is less likely to collide with any data from other cores also)

**Comment by dankcushions** [comment]
Sorry @joolswills , my above comment was wrong - it does use a sub-path (/mame2003/) for both system and save files. I've corrected my example above.

**Comment by joolswills** [comment]
aah thanks :)

**Comment by windale** [comment]
Thanks. Is a 'hiscore.dat' file included to save games or do we have to add our own ? If so where do we put it ? Also, shouldn't the samples folder be named 'samples' like every mame version has always used and not 'sample' ?

**Comment by dankcushions** [comment]
@windale why don't you try it and find out? From the code, /hsdb/ for hiscore.dat, and no it's "/sample/". that's what whoever originally ported this chose.

**Comment by windale** [comment]
You don't have to be sarcastic. I was asking because it's included with mame4all.in retropie. I thought it would be a part of the compile. I won't bother any more.

**Comment by dankcushions** [comment]
This issue can be closed now. All fixed by https://github.com/libretro/mame2003-libretro/commit/2ce1798e26d70efb29c047038fd6593d0e283f62

**Comment by S3riousSam** [comment]
Confirmed! Good work! Thanks!
