### ISSUE TITLE
Option to make player 2 joystick operate as player 1 second stick

### ISSUE THREAD

**Issue by jasonxbergman** [libretro/mame2003-libretro#158]
Feature suggestion: 

I'd like to be able to use the player 2 joystick as a second stick for player 1 in dual-stick games like Robotron or SMASH TV.

**Comment by rb6502** [comment]
You can do that very easily in standalone MAME on your PC/Mac/Linux, of course :)

**Comment by markwkidd** [comment]
There is code in this codebase related to the feature you are asking about. I'm just logging this for future reference!

**Comment by markwkidd** [comment]
It seems that this can be done via the MAME menu: https://github.com/libretro/mame2003-plus-libretro/issues/216

It might be nice to have a core option for people who do their controls purely in the frontend but I'm going to close this issue for now.
