### ISSUE TITLE
Altered Beast sprite problems

### ISSUE THREAD

**Issue by manuelmanuel** [libretro/mame2003-libretro#176]
Hi, Altered Beast is not playable because sprites don't leave the screen

**Comment by gamez-fan** [comment]
Hopefully the recent Sega core update will fix Altered Beast and quite a few other System 16
and system 18 games

**Comment by Metalwario64** [comment]
It happens to me as well on my Pi 3. I had to use mame2000 to play through it, but of course it has inferior sound.

**Comment by grant2258** [comment]
I can confirm this for rom altbeast and it does work properly on mame 078

**Comment by Darknior** [comment]
i confirm too. Same problem for me.

**Comment by grant2258** [comment]
been doing some reasearch seems it might be related to  musashi  m68k

**Comment by grant2258** [comment]
the m68000 shoyld be compiled with CFLAGS -std=gnu99

**Comment by grant2258** [comment]
fixed details here https://retropie.org.uk/forum/topic/16833/mame-2003-gamelist-xml-with-data-from-the-binary/12 

im not with github and makefiles but the fix is done if someone could fix the 68k core to compile then genereated code that would be great

**Comment by grant2258** [comment]
https://github.com/grant2258/mame2003-libretro/commit/9955f1c75066cb4b9c2c2b511ffbb64c5d3442a7 

if you wanna test it :)

**Comment by grant2258** [comment]
is causing the issue

M68KMAKE_OP(adda, 16, ., .)
{
        uint* r_dst = &AX;

        *r_dst = MASK_OUT_ABOVE_32(*r_dst + MAKE_INT_16(M68KMAKE_GET_OPER_AY_16));
}


M68KMAKE_OP(adda, 16, ., .)
{
        signed short src = MAKE_INT_16(M68KMAKE_GET_OPER_AY_16);
        uint* r_dst = &AX;

        *r_dst = MASK_OUT_ABOVE_32(*r_dst + src);
}

what fixes it in the new 68k core just in case anyone was wondering it is a gcc issue the above code at the to does work on gcc 3.4

**Comment by grant2258** [comment]
this thread can be closed the m68kcore fixed the issue
