### ISSUE TITLE
Mortal Kombat (mk.zip) announcer only says "Finish him"

### ISSUE THREAD

**Issue by nikkoman** [libretro/mame2003-libretro#195]
Apparently all phrases by the announcer are being replaced by "Finish him".

I played the ROM a few times last year with the same core and I don't remember this so it must be something new.

**Comment by gamez-fan** [comment]
My recent commit of the Williams sound core with the speedhacks added back in has caused this
only the T-unit version of this game is affected the Y-unit Mortal kombat will be fine, im sorry
i plain forgot about this.

Funny thing is this doesn't happen in MAME61 which was the last MAME build where these 
speedups were active, i guess it's time to revert these changes although they will benefit alotta
Midway  games performance wise on lesser hardware it's not good to break the sound in other
big name games in the process i'll fix this later today.

**Comment by gamez-fan** [comment]
Ok i've reverted the Williams sound changes that will fix the sound problems in Mortal Kombat
i suppose we can always leave them active in the seperate Midway libretro core for those that
maybe dont mind breaking the sound in one version of MK to get the performance boost
in loads of other Midway games.

**Comment by nikkoman** [comment]
Thanks! I updated from binary and it appears that it has not been compiled yet so I'm compiling right now...

**Comment by nikkoman** [comment]
Just updated/compiled from source, it's bc76b23 suffering from the same bug.

As for the Midway games, it soulds like a great idea to have a separate core that addresses those issues.

**Comment by gamez-fan** [comment]
Hi there the fix hasn't gone through yet check the pull requests

**Comment by barbudreadmon** [comment]
I recently dealt with speedhack on fbalpha through dipswitches (see https://github.com/libretro/fbalpha/commit/1d0a61c2cf5f36ad366364c43aa02cc3b5b553cc and https://github.com/libretro/fbalpha/commit/8b558dc11ad2c63cf2e5a0241c3dc1e2e47575cd), perhaps there is a way to handle the speedhack in midway game the same way ?

**Comment by gamez-fan** [comment]
Yeah i think @twinaphex wants a similar setup to the DCS hacks which can be turned on or off
via the Emulator options

**Comment by MariusRhinox** [comment]
Well, I updated again. The sound on the Y-unit Rev 4.0 version of Mortal Kombat is now completely broken as well.

**Comment by nikkoman** [comment]
I don't think there has been a revision since the problem occured. I believe it's being tracked because there have been several changes that may have caused it. Is it still bc76b23?

**Comment by MariusRhinox** [comment]
No idea. I updated through the RetroPie updater. Will have a look once I get home from work. Where would I see the version number, the Retroarch GUI?

**Comment by gamez-fan** [comment]
I just tested MK Y-Unit version and there are no sound issues my end at least, anyway there
is a new PR that similar to the DCS speedhacks will give users the option of disabling or enabling
the Williams speedhacks when playing the T-Unit version of Mortal Kombat.

**Comment by MariusRhinox** [comment]
While I’m still not sure where to find the version, RetroArch does list the build date as November 22, 2017, so it must indeed be something that happened outside of lr-mame2003 that messed it up for me. For clarification purposes; aside from some crackling, any sound that loops (ie: music, Raiden’s lightning effect) only plays for two or three seconds before restarting.

**Comment by nikkoman** [comment]
You can see the revision version when you enter the RGUI menu at the bottom.

**Comment by lostless** [comment]
I just updated from source version cf5f0b9. Turned off the midway speed hacks.  Still getting pops and clicks in the audio and some sound effects and music dropping out. So we are kinda out of the woods, but not like it was.

**Comment by gamez-fan** [comment]
Ok gimmie a min i know what's likely caused this my CPU overclock to fix NBA Jam with
the Williams speedups active

**Comment by msheehan79** [comment]
@lostless @gamez-fan I just updated my fork to enable/disable the NBA jam overclocking changes based on the Williams Speedhack core option. Could you try building from my fork to see if it resolves the issue? If it does I can create a pull request to add this to the main branch.

I tried it on my Windows x64 PC and the audio seemed OK on MK with this latest build and Williams Speedhack option disabled, with somewhat limited testing as it's rather late here! I noticed a couple clicks in the audio, but I also rebuilt a copy of Mame2003 from back in September (1980779) and I could hear it on that build too so I'm thinking that is more to do with my setup.

https://github.com/msheehan79/mame2003-libretro

**Comment by MariusRhinox** [comment]
Well, I downloaded that update. The option to turn off the Williams Speedhack is there, but... Now both T-unit and Y-unit versions have completely broken audio for me if I turn the speedhack off... Nothing but crackling and popping. Wasn’t like that before the speedhack got introduced, so I’m thinking you’re right about it being related to the overclocking.

**Comment by gamez-fan** [comment]
Hmm the Y-Unit games have no change in the CPU clocks, i've tested the Williams speedups on
two cores now and the sound problems should only really affect three games all of them T-Unit
are you sure there is not something else going on with your build that could be causing this..??

**Comment by MariusRhinox** [comment]
Could be, but it didn’t happen before the Williams speedhack was implemented, and only happens when I turn that off.

**Comment by gamez-fan** [comment]
Alright i concur with the above if you flip the speedhacks on then you get the sound problems
as reported for Mortal Kombat and NBA Jam, if however you turn off the speedhacks then a 
whole lotta Midway T-Unit and Y-Unit games have worse sound.

I think as the Williams sound core from MAME61 is built around the speedhacks the code isn't
really setup in such a way as to not use em, i wonder how the sound is for the DCS games should
users turn off the speedhacks in that core also..??

It's an all or nothing deal really either keep em active to get the preformance boost and a few games
as reported above will have some sound issues or totally revert the soundcore back to the version you
had previously.

Thats the only advice i can give really.

**Comment by MariusRhinox** [comment]
The DCS games are unaffected in my experience. No issues for MKII, MK3 or UMK3.

**Comment by rb6502** [comment]
Those speedhacks were removed because they *did* cause similar issues in MAME back in the day.  I particularly remember the MK announcer doing strange things for some people.

**Comment by gamez-fan** [comment]
Thanks very much for your input i had a feeling this was the case, but i wasn't sure if i had
made a mistake codewise when adding the speedhacks back into the Williams sound core.

**Comment by gamez-fan** [comment]
I seem to have always had a thing for crossing stuff off a list when done dunno why, but anyway
since this issue has now been resolved by reverting the speedhacks in Williams sound can we
close this now.??

**Comment by erniman** [comment]
Hello, I´ve updated my Recalbox to 17.12.02 and I had the MK sound problem (only says "Finish him"). I´ve read the previous comments but I don´t get how to fix it.
Can someone help me?
Thanks.

**Comment by dankcushions** [comment]
@erniman that's up to recalbox to update their builds. This issue is fixed in master - can this be closed?

**Comment by erniman** [comment]
Yes you can!
Thanks!

*Diego Iván Salvetti** Ingeniero en Telecomunicaciones*
Cel:+(549) 351-3928541 | Tel:+(54) 351-5681850 int.319
diegosalvetti@hotmail.com | erniman@gmail.com
www.diegosalvetti.com.ar


[image: Facebook] <http://www.facebook.com/erniman> [image: Twitter]
<http://www.twitter.com/erniman12> [image: LinkedIn]
<http://ar.linkedin.com/in/diegosalvetti> [image: about.me]
<http://www.diegosalvetti.com.ar/>
Contacto directo: [image: Google Talk] erniman@gmail.com [image: Skype]
 erniman
Get your own email signature
<https://wisestamp.com/email-install?utm_source=promotion&utm_medium=signature&utm_campaign=get_your_own>
