### ISSUE TITLE
Some games now not working after my commits

### ISSUE THREAD

**Issue by gamez-fan** [libretro/mame2003-libretro#197]
I propose we roll back the whole libretro-mame 2003 core to before my very first commit
as games have got broken in the process and i need more time to test and varify every
code change before they can be considered to be safe for the mainline.

Honesty i just followed the practices i've been using for 5 years now with my Xbox Arcade
sources i assumed the code with slight alterations for MAME78 use would be perfectly fine
but i realise now there is more work to be done to make the code endian safe.

Im sorry about this but in time i hope to make it right.

**Comment by nikkoman** [comment]
No worries, that's how programming works, especially in emulation.

Is there a despository with binaries I can download previous .so cores for the Pi?

**Comment by gamez-fan** [comment]
User problem rather than my code per say so close issues as there are none
