### ISSUE TITLE
problems since core updates / mame backports

### ISSUE THREAD

**Issue by joolswills** [libretro/mame2003-libretro#227]
There have been a fair few issues reported at the RetroPie site related to some of the recent changes to the core.

Since many of the changes seem to be untested, and technically can introduce new issues, I would like to suggest a new libretro core (or branch) is created for the hacks/backports and roll back this core to how it was before.

Then we can have the best of both worlds without the new regressions / compatibility issues.

In the meantime in RetroPie I have forked this repo and created a branch from around the 17th september, which I may switch to for RetroPie for now due to the issues reported.

**Comment by Darknior** [comment]
If we can choose what MAME core we want to use in the ES-SETUP ... why not, it's a good idea.
But it is not important for the common users. Nobody is using MAME core from source, it take time to compile, users are using BINary version.
Only testers are trying the source version to try games and compatibility.
If you only make a build when all is done, like you do for ES, it will be enough.

**Comment by joolswills** [comment]
In regards to retropie that is not true. Binaries are updated all the time and I cannot be expected to just know when things are "unstable" - master branch should not be used for experimental changes. Also for many platforms retropie is source only. From X86 to ODroid c2/xu3/tinkerboard and RPI on ubuntu etc.

**Comment by joolswills** [comment]
For EmulationStation we have a stable branch - which I specifically manage so that's not comparable.

**Comment by gamez-fan** [comment]
Can you link me to these "issues" as far as im aware there was one around Mortal Kombat
sound which is fixed now what were the others exactly.

**Comment by joolswills** [comment]
A few mentioned the mortal kombat sound - That's fully working now ? good news.

one user also mentioned narc - https://retropie.org.uk/forum/topic/14872/mortal-kombat-new-sound-issues-mame2003

There was a thread about a performance issues which you did some code changes for - https://retropie.org.uk/forum/topic/14756/retroarch-1-6-9-update-slowing-emulations-down/5

Many issues have been mentioned in reverts yourself too - so obviously many of the changes have introduced problems/regressions. If all the problems are resolved then good, but I suspect there will be more issues, and I think it would be useful to have a plain mame2003 core and a modified one.

**Comment by gamez-fan** [comment]
Sure i touched some video code in Toaplan 2 when adding the FixEight bootleg but that's not 
going to cause the kind of major performance issues he's reporting either in the game 
and certainly not with Console cores which are no way connected to this codebase

BTW from my testing of these games there is no performance change that i can see 
im confident on the MAME side at least we will have a stable build now but nothing is
100% in this world if there are issues im sure they can be squashed givin time.

**Comment by gamez-fan** [comment]
But seriously i have to laugh here some random users report some random problem with the
performance in there wait for it CONSOLE Emulators and somehow thats connected to code
changes i've done here in the MAME-2003 libretro core which last time i checked was not
responsible for SNES Emulation for example.

BTW just for the record it's two people posting about this and one other guy who's stating there
is no problem with his build after updating so i think it's strong case of jumping the gun here
surely we'd need at minimum 20 people reporting the same issue before a core revert would
be even considered.

I do suspect some people are on an agenda trip here all to keen it seems to blame my code for
anything that someone reports as broken in the latest RetroPie build, for exmaple their light bulb
goes out while playing Street Fighter II it must be related to my code changes :)

**Comment by gamez-fan** [comment]
Right ok i've opened a thread on the Rpi forum asking for people that bump into problems
related this core after updating to the latest version to report any issues they find, let's
see what if anything crops up and whether it can easily be fixed before resorting to 
core reverts.

**Comment by gamez-fan** [comment]
Right should this "issue" be closed now as it's been proven to have been user error rather
than my code changes which were to blame here.
