### ISSUE TITLE
Compile issues with latest updates

### ISSUE THREAD

**Issue by Ntemis** [libretro/mame2003-libretro#239]
http://dpaste.com/0PM7XBV
&
http://dpaste.com/3DJM28V

**Comment by twinaphex** [comment]
@gamez-fan this is something you will need to fix.

**Comment by gamez-fan** [comment]
@twinaphex yeah i think i see the problem i added sndhrdw/seibu in with the declerations for the
new driver i see now it has one already that all the seibu drivers must share i think my latest
commit will sort this.

As for PR's im sorry i cant get my head around this git so i'll do no further work on this core
i have no hard feelings about this and wish you guys all the best 

Regards!!

**Comment by Ntemis** [comment]
@gamez-fan  i don't understand why your frustration and your reaction signing off over a compile issue you easily fixed.
I understand you don't want or in any reason for, do a massive PR, so don't, no one if forcing it down your throat.  
What @twinaphex suggested is just that, a suggestion so you don't burden your self with hot fixes when these issues happen again and they will, no one is judging you here, because if you have a look in retroarch branch in closed issues only then you can and will get the whole picture.
He was only trying to protect you and we all learn from our own mistakes.
Please keep up the amazing work and thanks for your efforts to make this core better for all retroarch fans.

**Comment by gamez-fan** [comment]
Dont get me wrong here i've not taken the huff so to speak with anyone on here!! more at myself
for not being able to suss how to create a multi PR, as my currant method is not only messy but
it makes the travis check fail and obviously it's also more work for the guys as they need to merge
more PR's rather than one nice and tidy commit.
