### ISSUE TITLE
PS3 1.6.9 stable missing MAME2003 core

### ISSUE THREAD

**Issue by ertay** [libretro/mame2003-libretro#240]
## Description

Both CEX and DEX versions of the latest stable 1.6.9 build are missing the MAME2003 core. I installed the 1.6.7 nightly from September, and the MAME2003 core is there.

### Expected behavior

MAME2003 should be included in the cores list.

### Actual behavior

Missing MAME2003 core.

### Steps to reproduce the bug

1. Install latest stable 1.6.9 CEX or DEX
2. Load core
3. Only MAME2000 is there, no MAME2003.
### Version/Commit

- RetroArch: 1.6.9

### Environment information

- OS: PS3 CEX/DEX

**Comment by markwkidd** [comment]
@ertay I'm sorry to say this to you again, but in reality the repository where this problem is located is actually libretro-super, which controls the core buildbot.

Do you mind posting your issue there? https://github.com/libretro/libretro-super/issues
