### ISSUE TITLE
Request: Irem Sound Decryption

### ISSUE THREAD

**Issue by KMFDManic** [libretro/mame2003-libretro#246]
Note, I am not running this via an NES Classic/SNES Classic.  As of right now, the sound issues are present on my end.

"- 0.53: Bryan McPhail and Nicola Salmoria decrypted the sound CPU in Gunforce, Blade Master, Lethal Thunder, Undercover Cops, Mystic Riders, Major Title 2, Hook, R-Type Leo, In the Hunt and Perfect Soldiers.

27th July 2001: Nicola Salmoria decrypted the sound CPU in 'In the Hunt', Major Title 2 and Perfect Soldiers."

Thanks so much for all of your continued efforts in this truly phenomenal Arcade Core from Libretro:)

**Comment by gamez-fan** [comment]
Hmm this core is based on MAME78, as a result it should already have the code improvements
you mention above for the iremga20 sound.

Regards

**Comment by KMFDManic** [comment]
Yeah, I believed it should contain the code.  I am hoping it isn't some weird anomaly preventing it from working properly in the environment I am currently running it on.  Thanks a hell of a lot for all the games you added driver support for!  I am going to retest Irem today with latest Update.  Thanks!
