### ISSUE TITLE
Request: Driver Support for tcaveman (Tomy) Caveman

### ISSUE THREAD

**Issue by KMFDManic** [libretro/mame2003-libretro#248]
Support was added in MAME 0.184  Unfortunately, That rom set is incompatible with the NES Classic/SNES Classic, due to architectural conflcts with the pertinent Emulator.  Is there any chance, like you, @gamez-fan , did with Sengoku 3, etc, you can do backwards driver support for this specific game?  Thanks!!!  MAME 2003 is quite adept at handling CPU Intensive Games that otherwise bog down the system on MAME 2010, MAME 2014!  So, if this is a possibility, awesome!

**Comment by markwkidd** [comment]
Howdy @KMFDManic! You might have better luck getting a conversation going about this over in the mame2003-plus repository

**Comment by KMFDManic** [comment]
Hehe, @markwkidd This game is something someone has asked me about for quite some time.  Also, if you do not mind, send me a message on Reddit, again, under MDFMKanic.  I wanted to go over the high score dat with you, and a few other minor things.  I will continue the tcaveman on the other:)
