### ISSUE TITLE
Mame.ini ???

### ISSUE THREAD

**Issue by godzil21** [libretro/mame2003-libretro#27]
Hi Everybody!

I'm trying to change the sample rate of mame 2003 with the file mame.ini but I don't know where to put it . I have tried in different locations system directory, mame directory ...but without luck.

Does anyone knows where exactly to put the mame.ini ? 

Thanks a lot in advance!

**Comment by dankcushions** [comment]
There's no mame.ini - all mame system options have to be handled via the retroarch core options. It should be easy to add the sample rate as a core option though, which I'll try to do at some point.

**Comment by godzil21** [comment]
Thanks a lot !

**Comment by Alcaro** [comment]
Please don't delete and repost comments, it floods our email boxes. Use the edit button, or if it's important, post a new comment.

Core options work in all frontends that want them, they're not RetroArch specific. I'm not sure why dankcushions used that prefix.

**Comment by dankcushions** [comment]
Force of habit, but yes it's not retroarch specific, it's just exposing an option to the frontend, whatever that might be.
