### ISSUE TITLE
Night Slashers Reset Bug - US & Japan

### ISSUE THREAD

**Issue by KMFDManic** [libretro/mame2003-libretro#281]
Upon completing level 3, game resets before getting to level 4, in US and Japan versions.  Might this be protection related?  

Still absolutely loving the ability to play these previously stubborn, heavily encrypted games, though:)

Even as a 3 level demo, more than happy to have it, hehe.  Thanks in advance for anything done relative to this possible bug.

**Comment by gamez-fan** [comment]
Hmmm it's possible, i'll check the MAME WIP and look over the code for any mention of this
issue after i've tested the game to see if i can reproduce the bug.

**Comment by gamez-fan** [comment]
Hmm i just played to level 5 with no problems using nslashers.zip, i did make a change to the 
ARM CPU the other day maybe that fixed the reset bug..?? anyway grab the latest source
compile it and play the game again to see if your still getting the same issue.

BTW this core only supports the Korea, Japan, and Overseas versions of this game you'd
need a newer MAME to play the USA version as that was only dumped a year or so back.

Regards.

**Comment by KMFDManic** [comment]
@gamez-fan Using latest source, there are no more reset issues.  Thanks for actually taking the time to play the game to test this!  I can only imagine if a bug occurred on the final boss in a game, and one taking the patience required to attempt to reproduce the bug!  Myself and many others do truly appreciate Night Slashers as the Ultimate Xmas Gift, so thanks again man!  

If TOMY Caveman isn't an option, let me know, so I can close that issue as well!  

But, again, thanks for constantly improving and optimizing my personal favorite Arcade Core:)  Enjoy the Holidays!  And, great work on Wolf Fang!  Loving this stuff:)

**Comment by gamez-fan** [comment]
Hey no problem the ARM CPU update was actually to fix some Simpl156 games, i never knew
it would also fix a reset bug in Night Slashers there was no mention on the MAME WIP about
this so nice find and a big bonus it does so, 

As for TOMY Caveman the code is so different in later MAME builds it's more or less impossible
to backport the code to a core as old as this one in most cases unfortunately this is an example
of one of those cases im sorry buddy but it cant be done.
