### ISSUE TITLE
Roms not loading properly in Android core

### ISSUE THREAD

**Issue by nespcbuild** [libretro/mame2003-libretro#306]
I’m having a problem with the mame 2003 core for Android which I downloaded using the core updater inside of the Retroarch app. Many roms will load but are either missing graphics or will display a distorted image, then crash the Retroarch app. I am using the correct romset and the roms worked with previous versions of the core. The roms are non-merged and have been verified with clrmamepro. They also work in the current core for Windows. I can provide specific examples of roms that aren't working if needed.

**Comment by retro-wertz** [comment]
a list of affected games (better with their compressed names) would be really helpful in diagnosing along with screenshots and/or detailed description of how those games are behaving. and a comparison to other system usign the romset to isolate if this is an android issue or general core issue or just the romset.

**Comment by alfrix** [comment]
simpsn2p on android does not load checksum of file 6g and 7g return bad, the same rom works on the windows build (both using mame2003)

**Comment by nespcbuild** [comment]
1943 - Text appears but no other images, game repeatedly resets
sfau - foreground sprites are missing
splatter - loads to the image below which changes colors a few times, then RetroArch crashes

Images from current Android MAME 2003 core
![bad_1943](https://user-images.githubusercontent.com/23667697/34635313-fd4fbf54-f24a-11e7-9cda-251995f7dfe7.png)
![bad_sfau](https://user-images.githubusercontent.com/23667697/34635314-fd642a52-f24a-11e7-8553-f90c315745a5.png)
![bad_splatter](https://user-images.githubusercontent.com/23667697/34635315-fd776996-f24a-11e7-9199-323ddce3cf24.png
Screens from an older version of Android MAME 2003 core:
![good_1943](https://user-images.githubusercontent.com/23667697/34635316-fd88ebbc-f24a-11e7-8394-9dc1c9ede886.png)
![good_sfau](https://user-images.githubusercontent.com/23667697/34635317-fd9b5e32-f24a-11e7-85e0-7cafd8ca1194.png)
![good_splatter](https://user-images.githubusercontent.com/23667697/34635318-fdcf6830-f24a-11e7-9375-e101753d49db.png)

**Comment by nespcbuild** [comment]
Also, I copied over and tested the same exact files in Windows with the current core for Windows and they work fine there.

**Comment by arcadez** [comment]
Well there seems to be a common occurrence whereby games that should work in the version
of MAME this core was ported from do not work in this build, the problems can vary from inputs
to the graphics and or sound.

Diagnosing the cause and putting it right will be the tricky and time consuming part.

**Comment by markwkidd** [comment]
> I am using the correct romset and **the roms worked with previous versions of the core**.

I'm bolding an important section of the OP that some folks may be overlooking. This is a regression -- the core updated, and games that were previously playable are now unplayable.

Compiling Android cores seems to be kind of an ordeal and outside my experience, but that seems to be the way to go now, right? Bisect until the change is found where these regressions were introduced.

**Comment by markwkidd** [comment]
@arcadez I consider you among the experts on this core. do you have any further troubleshooting suggestions?

**Comment by arcadez** [comment]
@markwkidd you flatter me here as trust me im no expert on this core what so ever but it was
nice of you suggest otherwise ha ha, ok so we decided to reverted back to using the original 
libretro mame-2003 core are you saying you still have issues aftering downloading the latest
sources from here.??

**Comment by markwkidd** [comment]
@nespcbuild there have been some changes over the last 24 hours to this core. Could you try to download the newest compiled version of mame2003 and try the problematic ROMs again?

**Comment by nespcbuild** [comment]
I updated the core using the core updater and tried again but all 3 roms are having the same problems.

**Comment by arcadez** [comment]
Apart from this MAME core what else have you updated or has changed in your build..??

**Comment by nespcbuild** [comment]
I haven't really changed much else that I can think of. I first noticed the issue when setting up retroarch on a new Android device but I think I've ruled out the possibility of the new device being the culprit. On my older Android device where everything is working, I backed up the working core and updated to the current core to test without changing any other settings and had the same issue. After reverting back to the old core, everything was working again. The only other thought I had was that maybe there's some new requirement for the core that changed at some point after I downloaded the version that's working on my old device.

**Comment by arcadez** [comment]
I dont want to point fingers but i have an idea maybe as to what might be causing this issue
just putting two and two together really which is never good ;) but since the issues you reported 
are video problems in certain games im looking at recent commits that made changes to the
libretro video code.

Tell me when did you first notice this problem two weeks ago a month ago..??

**Comment by nespcbuild** [comment]
I first noticed the issues around the last week of November or maybe first week of December. However, I don't even know when the last time was that I updated the core before that. It may have been a year or more but I suspect that if it had been that long, others might have reported the issue by now.

**Comment by arcadez** [comment]
OK on spec try this source and see if the graphical issues are gone...

[url]https://www.sendspace.com/file/v5fxtl[/url]

**Comment by nespcbuild** [comment]
When I click that link it says "Wrong URL specified
Please check if you copied/entered the last characters of the file-link correctly"

**Comment by nespcbuild** [comment]
Nevermind I got it. Downloading now...

**Comment by nespcbuild** [comment]
I don't know how to build the core from those files. I've just been using the core updater inside of Retroarch

**Comment by nespcbuild** [comment]
OK nevermind again. I found the documentation on building it and I'll give it a shot

**Comment by nespcbuild** [comment]
Hopefully I'm following the correct documentation. I've completed the steps at https://github.com/libretro/docs for "Building" but am not sure what to do next to build the core. It says "The documentation will be built to the site directory" but I don't know where that directory is. Sorry but I have very little experience with compiling, building, programming, etc...

**Comment by arcadez** [comment]
It's ok buddy dont worry about it i'll ask someone over at my dev site but thanks anyway.

**Comment by markwkidd** [comment]
@nespcbuild could you try to download a fresh copy of the core to see if the problem has been resolved by some recent commits?

**Comment by nespcbuild** [comment]
I updated and tried again but I had the same results wit 1943 and splatter. sfau is now showing just a blank black screen.

**Comment by therealbungus** [comment]
dkong - audio messed up, colors and some sprites are wrong

donpachi, rtype, rtype2, simps2pa, simpsons, tmnt2, tmnt22p, and wjammers all refuse to load, just show a black screen.

nbajam and all of its clones or similar versions just show a corrupted mess of colorful pixels on load, makes a beep and then does nothing.

**Comment by bigleeow** [comment]
Same problems with the android mame2003 core and the mame2003 roms.  Some roms are mangled (dkong, dkongjr) some won't start (bublbobl, 1943).For the ones I can, I've switched to the mame2000 core and mame2000 roms, which seems to work.

**Comment by retro-wertz** [comment]
which would mean then that your roms are not verified to work for mame2003....

**Comment by therealbungus** [comment]
I've verified my files with clrmamepro, and the same roms work in retroarch
on the PC, so that is definitely not the problem.

**Comment by retro-wertz** [comment]
@therealbungus  after verification, did you check and make sure to remove the ones that are missing and/or incomplete? normally clrmame still creates the zip even if its incomplete until you do remove them. 
-whats the git version from the android core you are using and the pc
-what game (correct filename) that is causing issue.

**Comment by therealbungus** [comment]
Yes, the roms I'm using are the right ones, and are correct. I just tested
them out with the latest retroarch versions, 1.7.1 on Android and on PC.
Downloaded the latest mame2003 cores as of today.

**Comment by retro-wertz** [comment]
please answers based on the questions i asked so it would be easier to check. there are a lot of reason why something does not work and its a pain to trace without details.

**Comment by therealbungus** [comment]
Scroll up, I already said which roms I tested

**Comment by retro-wertz** [comment]
scroll up, you did not answer my question(s)

**Comment by SapphireTactician** [comment]
I'm having similar problems, seems like I opened a duplicate of this as #351 however mine also includes a video of the problem.

Lakka's version of the core runs the roms I'm using just fine, but no luck on Android.

**Comment by SapphireTactician** [comment]
Video of problem, recorded with Google Play Games screen recorder: https://streamable.com/u5e1j

**Comment by SapphireTactician** [comment]
I think we can close this as fixed now.

**Comment by grant2258** [comment]
only the namos1 is fixed I dont know about the other

**Comment by SapphireTactician** [comment]
All the games listed in the issue I opened work now as well.

**Comment by grant2258** [comment]
the tatio games as well ?

**Comment by SapphireTactician** [comment]
Yes

**Comment by SapphireTactician** [comment]
Sailor Moon as well

**Comment by grant2258** [comment]
That is really strange but good nothing changed anywhere else

**Comment by SapphireTactician** [comment]
I'll test some more games to be sure though

**Comment by nespcbuild** [comment]
The three roms that I reported issues with are all working now. Thanks to everyone who worked on resolving this.

**Comment by nespcbuild** [comment]
Of course.
