### ISSUE TITLE
@Twin Aphex

### ISSUE THREAD

**Issue by arcadez** [libretro/mame2003-libretro#307]
Do you want to rollback this core to what it was before i started dabbling with the codebase..??
i fully understand that for some folks this might not be a road they want to see this project head
down due to the troubles it can cause for some users and their romsets.

I have forked the build at this point and i plan to add to firstly add my NMK16 changes then
continue to maintain and update the code if and when doing so takes my fancy, at least then
folks can choose if they want a newer version of this core with all my backported game support
fixes and improvements or would prefer to just stick with the original MAME78 core.

**Comment by twinaphex** [comment]
we could rename this repo to mame2003-plus-libretro, and I could make another one that restores MAME 2003 to what it was before.

**Comment by arcadez** [comment]
Sounds like a good plan to me

**Comment by twinaphex** [comment]
@joolswills @dankcushions other participating parties -

the changes that @arcadez did have all been undone as per his request.

I have instead cloned the most recent copy with all his changes to a separate mirror repo -

https://github.com/libretro-mirrors/mame2003-plus-libretro/

I have only selectively backported the patches that were pushed which had nothing to do with @arcadez' changes. Let me know if everything is fine and well now.

**Comment by arcadez** [comment]
Can you put this description please i cant seem to do so myself...........

Updated 2018 version of MAME (0.78) for libretro. with added game support and many fixes and improvements

**Comment by joolswills** [comment]
Thanks. A good solution.

**Comment by arcadez** [comment]
@joolswills thankyou very much for adding the launcher script as quite honestly i would not have
known it was required, i've only ever worked on the MAME and FBA side of things.

Cheers!!

**Comment by markwkidd** [comment]
For my part I see mame2003-plus eventually superceding mame2003 'mainline' but it seems good to have a sandbox. I'm still waiting for the dust to clear with these backports but I'm willing to take on the task of making an updated DAT if no one else has by then.

Once we have a new DAT there will be less confusion for the user base about whether and how their MAME 0.78 ROM collections need to be updated.

**Comment by arcadez** [comment]
i've just added my final commits to the branch i plan to now go over them all again adding in
more documentation around what changes have been made and what versions of MAME the
code was backported from.

Regards!!

**Comment by arcadez** [comment]
Ok i've now after taking some advice from @dankcushions split off mame2003-plus from the
original mame2003 core so it can now be considered to be a seperate standalone core, due to
me hooking the Rpi setup files to my own branch of said core i no longer see any point in
keeping the mirror active @twinaphex would it worth just deleting it now.??

**Comment by markwkidd** [comment]
@arcadez would you consider closing this thread? :grinning:
