### ISSUE TITLE
Cinematronics Samples cause armora and starcas roms to have black screen 

### ISSUE THREAD

**Issue by vpelss** [libretro/mame2003-libretro#319]
Cinematronics Samples cause armoura and starcas roms to have black screen .

With no samples installed in \\192.168.1.109\share\bios\mame2003\samples the games work fine without sound.

When installed, I can get as far into the game as there is no sound. When sound is played, the screen goes black. No sound is ever heard.

I am using recalbox and have tried it with their two newest versions.

**Comment by markwkidd** [comment]
We had some issues with sample loading in 2018, and I believe that is the same bug that has affected you.

I just tested both of these games in the current MAME 2003 build and they seem to be working fine. Please post again if you are still having issues.
