### ISSUE TITLE
Trog crashes after pressing start

### ISSUE THREAD

**Issue by marcrobledo** [libretro/mame2003-libretro#323]
Game *Trog* makes RetroArch crash after pressing start.
Tested in RetroArch Windows.

**Comment by retro-wertz** [comment]
term2 and its variations should have the same crash as well. can you help confirm this on your end?

**Comment by marcrobledo** [comment]
Yes, term2 crashes too when trying to start game after coin insert!

**Comment by grant2258** [comment]
must be a windows issue works fine on my pi

**Comment by retro-wertz** [comment]
Trog should have less chance of crashing, but still will crash... term2 (uses similar mame driver) though crashes most of the time.

running under windows and linux, if its not a problem with pi, then something during compile probably is missing.

**Comment by grant2258** [comment]
ill try trog term2 is 100% ok  you using 32 or 64 bit ?

**Comment by retro-wertz** [comment]
64bit. i should have a backtrace in another issue that shows when it
actually crashes.

**Comment by grant2258** [comment]
are you compiling with -m32 ?

**Comment by retro-wertz** [comment]
probably not, or not sure. im compiling whatever the stock makefile offers
for the current system (win or linux atm)

**Comment by grant2258** [comment]
the ym2151 update should have fixed this can we close if the issue is gone

**Comment by marcrobledo** [comment]
I confirm it's fixed, thank you :-)
