### ISSUE TITLE
How to run on an android phone？

### ISSUE THREAD

**Issue by h923745834** [libretro/mame2003-libretro#330]
This should be how to compile into the app, and then run on an android phone?

**Comment by dankcushions** [comment]
you install retroarch app and it should appear in the core updater ? does it not?

**Comment by h923745834** [comment]
@dankcushions I'd like to compile in eclipse or android studio this project into an android project

**Comment by dankcushions** [comment]
The makefiles already compile to android succesfully: https://buildbot.libretro.com/nightly/android/latest/armeabi-v7a/

you can open the code in whatever IDE you want and you should be able to compile to anything supported by the makefiles, however it's a libretro core so you will need to run it via retroarch (or equivalent). it's not a standalone android emulator.

**Comment by h923745834** [comment]
@dankcushions thank you for your replay.I am a android beginners, I'd like to put the MAME source into android studio  IDE to generate  . So file, and then through Java jni calls. I do not know is there this kind of case, where can I find?

**Comment by markwkidd** [comment]
@h923745834 could I suggest that you post your question to the libretro forums at http://forums.libretro.com/ ?

I don't think that anyone who watches this github repository has experience doing what you would like to do, but you may have more luck on the libretro forums.
