### ISSUE TITLE
Fixing Game Crash on the Nintendo Switch Device

### ISSUE THREAD

**Issue by natehaxx** [libretro/mame2003-libretro#339]
https://github.com/libretro/mame2003-libretro/blob/6a01d2901769b3a2a7c677ba58f30b981a66701a/src/libretro/libretro.c#L212

is causing the issue for the zip files not to load.

static void update_variables(void)
{
    struct retro_variable var;  needs to be replaced with

static void update_variables(void)
{
    sample_rate = 48000;
    return;
    struct retro_variable var;

its not a proper fix but it does its job

**Comment by markwkidd** [comment]
The crash should be fixed by this commit: https://github.com/libretro/mame2003-libretro/commit/0be59fe5bf6be08615356b739d6906cb64b5a3a9

Can you test with with a version more recent than that?

**Comment by hizzlekizzle** [comment]
closing. feel free to open it back up if the problem persists
