### ISSUE TITLE
Enable Save States/Load States options

### ISSUE THREAD

**Issue by dagreatbuzzsaw** [libretro/mame2003-libretro#343]
Exactly as the title says, that is, if it is possible.  Thanks!

**Comment by dankcushions** [comment]
what do you mean? you can save in some mame2003 games already: https://github.com/RetroPie/RetroPie-Setup/wiki/lr-mame2003#save-states

**Comment by dagreatbuzzsaw** [comment]
Yes, but not for the MK games (which is the main reason I use this core).  When I use the hotkey for Save States the message at the bottom says, "Core does not support save states".  I just figured that Save State support wasn't added in yet.  I didn't know it just worked for certain games.  I'm sorry.

**Comment by dankcushions** [comment]
i'm afraid that's likely impossible. we're limited by how mame as it was in 2003. you could try a more up-to-date mame core?

**Comment by dagreatbuzzsaw** [comment]
Believe me, I want to.  MAME 2009 would have been perfect, but while the first MK seems to be working fine (albeit the audio skips a bit), MKII and UMK3 suffers from very severe slowdown upon starting up.  I mentioned this on the "MAME" page (as I could not find a specific page for MAME 2009), only to be told that I was better off with MAME 2003.  Here is where I reported the issue:

https://github.com/libretro/mame/issues/62
