### ISSUE TITLE
diehard requires a commandline or .ini to boot

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-libretro#347]
As documented by @grant2258 starting here: https://retropie.org.uk/forum/post/139011

In order to use `diehard` with MAME 0.78, one must use the command line `mame diehard -bios us`. There is an equivalent setting that can be used with an `.ini` file -- also not an option with MAME 2003.

The OP points out the BIOS selection code in `common.c` at `int determine_bios_rom(const struct SystemBios *bios)` which seems like a good place to continue the investigation when time allows.

**Comment by grant2258** [comment]
this is called on rom_load()  same file common.c

/* determine the correct biosset to load based on options.bios string */
	system_bios = determine_bios_rom(Machine->gamedrv->bios)

I know nothing about retroarch api. Thats something im planing to change but all that would need do is a bios flag settable in retroarch options and set bios.options
