### ISSUE TITLE
some games need fixed up for the xml generator

### ISSUE THREAD

**Issue by grant2258** [libretro/mame2003-libretro#352]
There is a a few drivers that are using romload no-dump that is causing merge failures and causing the the roms not merge properly in there parent/child format in the mame dat. 

I have fixed these up in mame2003-plus and can do the same fixes for here mark had to edit it by hand before if you would like these fixes let me know its ok to go ahead. there are no new roms created just fixed the parent clone relationships up by changing the nodump to baddump. You will just need to rescan your roms and it will auto fix. I think its only 5 sets all in that do it. There roms are made playable in mame by using roms from another set it was just implemented bad at the driver level

**Comment by markwkidd** [comment]
I'm sorry I missed this Issue till now @grant2258 if you have time to bring those changes to mame2003-libretro please and thank you!
