### ISSUE TITLE
spiderman and arabian fight very slow ..

### ISSUE THREAD

**Issue by cecilmax** [libretro/mame2003-libretro#354]
Hello, i try to run spiderman and arabian fight on wii with retroarch 1.7.1 and it is very slow, sound and graphics are in slow motion. Any idea how to fix it ?

**Comment by dankcushions** [comment]
what hardware? if it's the wii as in your other issues, you can expect many games to be slow. weak CPU.

**Comment by cecilmax** [comment]
Ah ok, so on Wii U it should be better ?

**Comment by dankcushions** [comment]
sure, better. on a raspberry pi 3 some games have performance issues, but i don't know how that compares to the wii u's powerpc cpu. i expect you'll need to get an x86 cpu for all games to be full speed.

mame is a cpu intensive emulator and even this ancient version asks for a lot of power in some games. and is only able to use a single cpu core.

**Comment by grant2258** [comment]
there was a problem slowing things down it will be fix also check here mame2003 had this setting on for me slows things down see here https://github.com/libretro/mame2003-plus-libretro/issues/175

**Comment by markwkidd** [comment]
@cecilmax I'm going to close this issue but if you have further questions or discussion please feel free to reopen it and we will continue on.
