### ISSUE TITLE
found a very intresting problem with mame for 64 bit

### ISSUE THREAD

**Issue by grant2258** [libretro/mame2003-libretro#355]
ive been working on splatter house and its been driving me nuts. I got to a point where I though ill use gdb and see whats going on and here is what happend spatter house was working properly. I believe the compiled flags are set bad for the x86/x64 possibly android as well and is causing these issues. 

To get spatter house working do this edit the makefile change the  first line DEBUG=0 to DEBUG =1 

then do a make clean compile again and it magically works

**Comment by retro-wertz** [comment]
compile flags or specific sections of the code that needed this "no optimization" during compile (as the case for splatterhouse). i remember a similar section in fba that needed similar to this ( i think that was qsound? ), and that portion had to be compiled without optimization.

**Comment by dankcushions** [comment]
we found a similar issue on ARM - https://github.com/libretro/mame2003-libretro/issues/22

solution was to downgrade O3 optimization to O2, however that was stopping a segfault, not bugs.

**Comment by grant2258** [comment]
the segfault was probably the ym2151 that was patched some info on that thread might help find the problem

**Comment by grant2258** [comment]
look like i could loose its scope the way this code is written

WRITE_HANDLER( namcos1_paletteram_w )
{
	namcos1_paletteram[offset] = data;
	if ((offset&0x1fff) < 0x1800)
	{
		if (offset < 0x2000)
		{
			sprite_palette_state[(offset&0x7f0)>>4] = 1;
		}
		else
		{
			int i,color;

			color = (offset&0x700)>>8;
			for(i=0;i<MAX_PLAYFIELDS;i++)
			{
				if (playfields[i].color == color)
					tilemap_palette_state[i] = 1;
			}
		}
	}
}

this would be safer code for optimization

WRITE_HANDLER( namcos1_paletteram_w )
{
	namcos1_paletteram[offset] = data;
	if ((offset&0x1fff) < 0x1800)
	{
		if (offset < 0x2000)
		{
			sprite_palette_state[(offset&0x7f0)>>4] = 1;
		}
		else
		{
			int color;

			color = (offset&0x700)>>8;
			for(int i=0;i<MAX_PLAYFIELDS;i++)
			{
				if (playfields[i].color == color)
					tilemap_palette_state[i] = 1;
			}
		}
	}
}

I notice this problem in the loops for the draws as well. Ill tidy the code up when i wake up just done a nightshift and see if that helps

**Comment by grant2258** [comment]
just to clarify a little these gfx glitches dont happen on the pi only x86 and the android just displays a rainbow type effect. I dont know the exact details on the android as i dont use this build.

**Comment by SapphireTactician** [comment]
On Android 7 (32-bit) RetroArch crashes when loading `splatter`. Figured I'd mention that in case I haven't already.

**Comment by grant2258** [comment]
relive it or not a crash is easier to debug I wonder if anyone could debug the andriod version and see whats going on. Im going to start investigating. Just because splatter crashes it doesnt mean its the cause it could be but cant rule other things out

**Comment by grant2258** [comment]
https://github.com/libretro/mame2003-libretro/pull/356 if this pull is accepted let me know if the android problems go away. Its better to just not optimize the one routine function thats causing it

**Comment by SapphireTactician** [comment]
Will do

**Comment by retro-wertz** [comment]
/home/deepin/Desktop/Screenshot_2018-04-06-02-50-30.png

**Comment by SapphireTactician** [comment]
How do I try this out on my Android phone?

**Comment by arcadez** [comment]
Fan-dabi-dozy

**Comment by SapphireTactician** [comment]
Looks like I was able to simply download the new version from the Core Updater within RA. All is well now! Hurray!

**Comment by grant2258** [comment]
glad it all worked out now time for bed
