### ISSUE TITLE
MAME sees double-inputs when RetroPad is actually a keyboard--blocks <CODE_NOT> mapping

### ISSUE THREAD

**Issue by caver01** [libretro/mame2003-libretro#37]
Player controls that originate as keyboard inputs configured in RetroArch are received TWICE by MAME--once as a RAW key, and again as the virtual RetroPad input. This can be revealed by attempting to create custom keymaps in the MAME GUI. It is a problem because it prevents complex mapping using the <CODE_NOT> technique. It affects anyone using a keyboard interface such as the common Ultimarc IPAC family of controllers (older versions are keyboard interfaces, newer versions can be set as keyboards or joypads via firmware).

For example, assume you have the LEFT ARROW mapped bound in RetroArch to Player 1 Left. If you bring up the MAME GUI, configure input (this game), select an input, and press ENTER, MAME waits for your input key. Press the LEFT Arrow and you get TWO inputs mapped as a <CODE_AND>. Instead of just `LEFT`, or even `RetroPad1 Left`, you get both: `LEFT RetroPad1 Left`. This is a problem because it prevents you from setting up <CODE_NOT> mappings. You cannot, for example, setup a single-joystick "tank stick" . If you wanted to map input to "up, not left" you normally hit ENTER on the input, then tap the joystick UP followed by LEFT LEFT. This does not work.

For more detail and examples, check [this discussion](https://retropie.org.uk/forum/topic/378/configuring-code_not-control-mapping-in-lr-mame2003) on the RetroPie forums.

**Comment by dankcushions** [comment]
From my post on the forum:

the problem is, mame is reading from the abstracted retropad and retrokeyboard. it doesn't know that they are the same key, because they are already abstracted at that point. i don't believe there's a point where you can do a comparison to see if they're the same key.

this seems like something that's best solved through configuration - if you want to avoid the double presses you should change the default binding of (for example) LEFT ARROW from RetroPad1 Left, or change it to 'null'.

**Comment by pedrovelho** [comment]
I have the same issue different example, I have some friend that like to use the keyboard others the joystick. We would like to have, at least for mame roms like street fighter, player 1 mapped both to keyboard and RetroPad1, however buttons are mixed up and each time we try to fix the keyboard key overwrites the retropad custom key we would like. I will try to reset emulationstation configuration and not configure the keyboard at all on emulationstation to see if I can get rid of this problem and let you know.

**Comment by markwkidd** [comment]
@caver01 and @pedrovelho the latest builds of mame2003-plus have a new core option called "Input interface" which allows you to select between `retropad`, `legacy`, and `simultaneous`.

`retropad` only reads input through the retropad abstraction. With default RetroArch settings, as has been mentioned, the retropad abstraction includes a mapping for player one on the keyboard.

`legacy` this only uses the libretro keyboard api to pass keyboard input directly to the MAME keyboard input system.

`simultaneous` is the 'classic' mame2003 behavior. both input systems simultaneously, including when they overlap.

**Comment by grant2258** [comment]
@hawkeye3123  that becase he is talking about mame2003-plus not mame2003

**Comment by hawkeye3123** [comment]
@grant2258 I know, I installed mame2003-plus but don't know how to change the button mapping or the input interface within it.

**Comment by grant2258** [comment]
https://retropie.org.uk/forum/topic/17766/mame2003-plus-250-new-games-new-input-system-new-features-new-bugs/355

if you want to use keyboard only choose keyboard

**Comment by markwkidd** [comment]
@dankcushions do you think it would be good to implement port over the core option -based solution from mame2003-plus to this core? I don't have any other ideas for fixing this.

**Comment by markwkidd** [comment]
Indeed I have now ported over the core option from mame 2003-plus. At the moment the core option defaults to `simultaneous` unlike in Plus where the default is `retropad`
