### ISSUE TITLE
Backport MIPS3/Killer Instinct to ARM and x86_64 platforms

### ISSUE THREAD

**Issue by markwkidd** [libretro/mame2003-libretro#38]
<removed comments from before the regression was identified, for the sake of understandability in the future>

**Comment by dankcushions** [comment]
are you using the latest nightly build? because you should have no problem finding the .chd in the current build. that part of my log looks like this:

```
RetroArch [libretro INFO] :: Found game: blitz [blitz].
RetroArch [INFO] :: Environ SYSTEM_DIRECTORY: "/Users/chris/Work/System".
RetroArch [INFO] :: Environ SAVE_DIRECTORY: "/Users/chris/Work/Save".
RetroArch [INFO] :: Environ SET_ROTATION: 0
RetroArch [libretro INFO] :: osd_fopen (buffer = [/Users/chris/work/Roms/blitz/sound102.u95]), (directory: [/Users/chris/work/Roms]), (path type dir: [rom]), (path type: [1]), (filename: [blitz/sound102.u95]) 
RetroArch [libretro INFO] :: osd_fopen (buffer = [/Users/chris/work/Roms/blitz.zip]), (directory: [/Users/chris/work/Roms]), (path type dir: [rom]), (path type: [1]), (filename: [blitz.zip]) 
RetroArch [libretro INFO] :: osd_fopen (buffer = [/Users/chris/work/Roms/blitz/blitz1_2.u32]), (directory: [/Users/chris/work/Roms]), (path type dir: [rom]), (path type: [1]), (filename: [blitz/blitz1_2.u32]) 
RetroArch [libretro INFO] :: osd_fopen (buffer = [/Users/chris/work/Roms/blitz.zip]), (directory: [/Users/chris/work/Roms]), (path type dir: [rom]), (path type: [1]), (filename: [blitz.zip]) 
RetroArch [libretro INFO] :: osd_fopen (buffer = [/Users/chris/work/Roms/blitz/blitz.chd]), (directory: [/Users/chris/work/Roms]), (path type dir: [image]), (path type: [2]), (filename: [blitz/blitz.chd]) 
RetroArch [libretro INFO] :: osd_fopen (buffer = [/Users/chris/Work/Save/mame2003/diff/blitz.dif]), (directory: [/Users/chris/Work/Save/mame2003/diff]), (path type dir: [diff]), (path type: [3]), (filename: [blitz.dif]) 
RetroArch [libretro INFO] :: osd_fopen (buffer = [/Users/chris/Work/Save/mame2003/diff/blitz.dif]), (directory: [/Users/chris/Work/Save/mame2003/diff]), (path type dir: [diff]), (path type: [3]), (filename: [blitz.dif]) 
RetroArch [libretro INFO] :: osd_fopen (buffer = [/Users/chris/Work/Save/mame2003/diff/blitz.dif]), (directory: [/Users/chris/Work/Save/mame2003/diff]), (path type dir: [diff]), (path type: [3]), (filename: [blitz.dif]) 
RetroArch [libretro INFO] :: osd_fopen (buffer = [/Users/chris/Work/Save/mame2003/diff/blitz.dif]), (directory: [/Users/chris/Work/Save/mame2003/diff]), (path type dir: [diff]), (path type: [3]), (filename: [blitz.dif]) 
RetroArch [libretro INFO] :: osd_fopen (buffer = [/Users/chris/Work/Save/mame2003/diff/blitz.dif]), (directory: [/Users/chris/Work/Save/mame2003/diff]), (path type dir: [diff]), (path type: [3]), (filename: [blitz.dif]) 
RetroArch [libretro INFO] :: osd_fopen (buffer = [/Users/chris/Work/Save/mame2003/cfg/default.cfg]), (directory: [/Users/chris/Work/Save/mame2003/cfg]), (path type dir: [cfg]), (path type: [9]), (filename: [default.cfg]) 
RetroArch [libretro INFO] :: osd_fopen (buffer = [/Users/chris/Work/Save/mame2003/cfg/blitz.cfg]), (directory: [/Users/chris/Work/Save/mame2003/cfg]), (path type dir: [cfg]), (path type: [9]), (filename: [blitz.cfg]) 
RetroArch [INFO] :: Environ SET_PIXEL_FORMAT: RGB565.
RetroArch [libretro INFO] :: game bpp: [16], system bpp: [16], color format [RGB565] : SUPPORTED, enabling it.
RetroArch [INFO] :: Skipping SRAM load..
```

however the game, and any other .chd games doesn't work, but not for reasons yours don't. they just display garbled screens for me. i think we need to prove that standalone mame2003 works with them fine before spending any time on it.

**Comment by markwkidd** [comment]
According to the MAMEDev wiki, more than a couple of CHDs should be working with 0.78. I just looked at the release notes for 0.77 and 0.78 (so this is a partial list). It seems like this list should be a good starting point for testing:

**New Games supported or promoted from GAME_NOT_WORKING status**
- Mace - The Dark Age
- Blitz '99
- CarnEvil 
- Wayne Gretzky's 3D Hockey
- Judge Dredd (Rev C)
- Judge Dredd (Rev B) 

I'm using the latest Lakka nightly build (2016-06-07). Lakka is the only way that I've used Retroarch so far, and I'm not sure it's going to be practical for me to update the Core with this setup. Please correct me if that's mistaken.

I do have a Windows 10 environment available and I'll try to set RetroArch up to test it there.

**Comment by markwkidd** [comment]
I'll be darned, this does look like an issue with the version of the MAME 2003 core that Lakka uses. 

It turns out that there is a way to copy a core into the /tmp/cores folder in Lakka. I downloaded the current Linux x64 mame2003_libretro.so from the buildbot, and things look to be working as expected now.

What would be the protocol in terms of pushing this issue to Lakka? I'm not too familiar with github -- is there a way to move this thread over there, or should I create a new issue that references this one?

**Comment by dankcushions** [comment]
When you say working as expected, you mean loading .chd games and running them? I can't get it to work with the latest on either OSX or linux!

**Comment by markwkidd** [comment]
Wayne Gretzky's 3D Hockey seems to be working fine with me using the buildbot core, as opposed to the current Lakka core. Have you tried that one?

**Comment by dankcushions** [comment]
you're right! wg3dh works. killer instinct 1 and 2 don't load for me (beyond the coloured screen) - assuming it's not just me, there must be some specific with their drivers. i think probably something went wrong in the transition from the regular mame core and libretro, or maybe some deprecated code. i'm not sure how to debug/fix that :(

**Comment by markwkidd** [comment]
Someone in the MAME IRC channel was able to provide me with a copy of the original MAME 0.78 windows executable, since the mamedev.org archive has a dead link for that file.

I can confirm that Killer Instinct works with the original MAME 0.78. I'm attaching mame078b.zip for other folks to reference.

So there seem to be two unrelated issues:
1. Lakka is using a MAME 2003 core that -- unlike the current buildbot mame2003-libretro -- can't find CHD files. I can file an issue for Lakka about it -- probably not a challenge to deal with this.
2. The other issue is an apparent regression in mame2003-libretro that means one or more games which run in vanilla 0.78 do not in MAME 2003. This issue may be more tricky, as you say.
[mame078b.zip](https://github.com/libretro/mame2003-libretro/files/344585/mame078b.zip)

**Comment by markwkidd** [comment]
I have updated the title, and added a new table to the OP. From a more thorough test (working backwards through the alphabet) it seems that 0.78 has good support for its CHD games. This is in contrast to the MAME 2003 core, presumably due to some regression during the conversion process or in some subsequent update?

**Comment by markwkidd** [comment]
I couldn't handle seeing the table incomplete, so I went ahead and finished the 0.78 column.

The MAME 2003 column of the OP table needs to be fleshed out, but it will be a few days till I can get back to my Lakka environment. @dankcushions maybe you already know whether those ROMS and CHDs work in mame2003-libretro?

**Comment by dankcushions** [comment]
made a start! everything tested in latest version of lr-mame2003 (actually it's my current PR - https://github.com/libretro/mame2003-libretro/pull/41 - but that shouldn't make a difference):
**a51mxr3k:** works
**area51:** works
**area51mx:** works
**biofreak**: works (takes AGES to load on my pi3, though)
**blitz**: works (takes AGES to load on my pi3, though)
**blitz2k**	: works (takes AGES to load on my pi3, though)
**blitz99**: works (takes AGES to load on my pi3, though) 
**bm1stmix**: works (takes AGES to load on my pi3, though)
**bm2ndmix**: works (takes AGES to load on my pi3, though)
**bm2ndmxa**: works (takes AGES to load on my pi3, though)

after these successes, i double-checked the killer instinct games to make sure they definitely didn't work:
**kinst**: doesn't work (i left it for a good 10 minutes so reasonably sure!)
**kinst2**: doesn't work (i left it for a good 10 minutes so reasonably sure!)

i'm beginning to suspect it's some bug with a few of these boards (kinst1 + 2, and more?) rather than anything specifically to do with CHDs.

**Comment by markwkidd** [comment]
Just when I think I've figured out an accurate title for this issue. :) I added your testing results to the OP table.

It really is starting to look like a cluster of unrelated minor issues that happen to involve CHDs.

**Comment by Laddyacris** [comment]
hello @dankcushions 
I upload chd file (blitz) in my folder /roms/mame/ on my rpi3 and rpi2 
I have a good romset (Mame 0.78) and the last mame core
when I launch game, I have a blue screen. The game doesn't launch. Why ?

**Comment by dankcushions** [comment]
@Laddyacris 
.chd images should be placed in subdirectories within the `/libretro content dir/` ROM directory e.g.:
if you have your blitz.zip in
```
/libretro content dir/blitz.zip
```
the chd should be in:
```
/libretro content dir/blitz/blitz.chd
```

**Comment by Laddyacris** [comment]
my paths are : (on recalboxOS)
/roms/mame/blitz.zip
/roms/mame/blitz/blitz.chd

**Comment by dankcushions** [comment]
@Laddyacris 
it's right, but i don't know what version is in recalbox - you should have the latest nightly to be sure it's going to work.

also, the CHD games take a LONG time to load (10 minutes maybe), and blitz will be 1fps and not playable on a pi3 anyway.

**Comment by Laddyacris** [comment]
Oh, rpi3 is not powerfull enough. Thanks for your replie.

**Comment by dankcushions** [comment]
A to-do for me/someone: go back to earliest commits and see if KI EVER worked in the libretro version. if it works in standalone, it might be possible to isolate it to a specific commit in this version (hopefully not the first :))

**Comment by elmojatota** [comment]
Get the latest ROM  for both games, along with the latest CHD 
Use mame2014.so core

Games should load fine. Mine are working with latest lakka on PC

**Comment by markwkidd** [comment]
@elmojatota the MAME 2003 core is the arcade emulator of choice for low-power devices like the rPi family. On those hardware platforms MAME 2003 works fine but MAME 2014 runs too slowly to use. It is good to know that Killer Instinct is working with it however, for people who do have more powerful hardware at their disposal.

**Comment by a7mag3ddon** [comment]
Just seen a video of K. I running under mame 2003 on You tube, any ideas how it was done?

**Comment by elmojatota** [comment]
Can you share the link?

**Comment by a7mag3ddon** [comment]
Yes of course, didn't k ow if it was allowed

https://youtube.com/watch?v=-nNJnArwyrY

**Comment by dankcushions** [comment]
a lot easier to fake than to do. it loads fine in advmame on a pi3 but has terrible performance. i don't see how that gets fixed without writing an arm dynarec or whatever.

**Comment by a7mag3ddon** [comment]
Yes can be faked but it's from a respected retropie modder called MadLittlePixel (MLP) so I'm not somaure it is a fake to be honest.

**Comment by a7mag3ddon** [comment]
Could it be done by decompressing the CHD somehow and using a special mame compile ?

**Comment by dankcushions** [comment]
if it's true then he needs to release his source code under the gpl :) i don't want to speculate.

**Comment by santiagomoneta** [comment]
there was no updates on this?

**Comment by markwkidd** [comment]
There are no coders actively working on this issue. Unfortunately no one yet has stepped forward with the skills necessary to figure it out.

This might be a good issue to set up a bounty for now that libretro has a bounty system in place.

**Comment by r-type** [comment]
@dankcushions  @markwkidd 
>A to-do for me/someone: go back to earliest commits and see if KI EVER worked in the libretro version. as it works in standalone 2003, it might be possible to isolate it to a specific commit in this libretro version (hopefully not the first :))

Hum Sorry but I think it's not a regression.
let me explain , At this time (2003 mame0.78 ) the only working implementation of kinst was using mips3 DRC . 

I think the binary you point (official mame078 windows)  was compiled with the DRC support
```
# uncomment next line to use DRC MIPS3 engine
X86_MIPS3_DRC = 1
```
But sadly at this time (2003) , there were only an DRC implementation for X86 (not for X64).

So now regarding the libretro implementation the X86_MIPS3_DRC = 1 was commented
 (see https://github.com/libretro/mame2003-libretro/blob/master/Makefile#L279 )
You can uncomment it , to make it work ,  but then you will have to build a 32 bit core.
after using a 32 bit core with mips3 DRC , kinst will work.
 
![kinst2003](https://user-images.githubusercontent.com/3614417/27458233-582ec552-57a8-11e7-8565-1737774fc1a5.png)

Now I don't think it will be possible to backport **easily** the X64 DRC backend for mips3 into the 0.78 as it was done in later mame release.

**Comment by hizzlekizzle** [comment]
That's some grade-A detective work, r-type! We can probably put a conditional into the makefile so 32-bit users can benefit, which includes the vast majority of ARM users.

**Comment by markwkidd** [comment]
Thanks @r-type !

Given that there may be other issues with x64 compilation (https://github.com/libretro/mame2003-libretro/issues/83) does it ever make sense to compile MAME 2003 for 64 bits? Maybe it should always be 32 bit?

**Comment by dankcushions** [comment]
great work @r-type! for anyone curious, I un-commented the line and recompiled on RPI3. kinst and kinst2 segfault, which is to be expected on ARM.

kinst/2 does work (slowly) on advmame, so we could maybe look at back-porting their mips code: https://github.com/amadvance/advancemame/tree/master/src/cpu/mips - i presume ARM there uses the standard mips3.c, but not sure.

at some point, i'm not so interested in porting it if no ARM cpu exists that will run it well :)

**Comment by markwkidd** [comment]
Hey. I tried to fix things: https://github.com/libretro/mame2003-libretro/pull/104

**Comment by markwkidd** [comment]
I am going to close this issue now -- what a trip it's been. It does feel like bugfixes for the current MIPS3 code and/or discussion of an ARM dynarec should be in a fresh new issue.

**Comment by mpalpha** [comment]
random pastebin found with arm optimizations.
https://pastebin.com/2t5Mf6SC
