### ISSUE TITLE
krull, screwloo - retroarch.exe has stopped working everytime retroarch closes

### ISSUE THREAD

**Issue by arnoldsecret** [libretro/mame2003-libretro#380]
title.
![untitled](https://user-images.githubusercontent.com/41223243/46571590-1fcdbb80-c9aa-11e8-9a8f-392466beecb9.png)

**Comment by grant2258** [comment]
all the cores had to rebuild a day or 2 ago maybe more  you might have an older version of mame2003 installed while this was happening try updating the mame2003 core im having no issues here. with todays latest ra source or on 1.7.3

mame2003 should be on commit  355ca5d

**Comment by markwkidd** [comment]
@arnoldsecret can you update your mame2003 core and try again? this should be fixed

**Comment by markwkidd** [comment]
Two of us have checked with a recent commit and found this to be fixed so I will close this issue.
