### ISSUE TITLE
DCS games (MK2, etc) slowly overflow(?) the buffer, periodically distorting sound [$60]

### ISSUE THREAD

**Issue by dankcushions** [libretro/mame2003-libretro#43]
Tested on Raspberry Pi 3 and OSX x64, and the DCS speedhack on/off, with same results.

If you play MK2 for around 10 minutes, it will start to distort the audio (heavy buzzing and overlapping samples), for about a minute, before eventually settling down, but with an ever increasing audio latency. if you keep playing for another 10 minutes, the process will repeat, with the latency getting worse and worse.

i debugged this by enabling all the various logs in dcs.c here https://github.com/libretro/mame2003-libretro/blob/master/src/sndhrdw/dcs.c#L13, and replacing all `logerror(..)` with `printf(..)`. this prints a variety of info to the console. mostly a lot of this:

```
DCS dac update: bytes in buffer = 398
DCS dac update: bytes in buffer = 531
DCS dac update: bytes in buffer = 424
DCS dac update: bytes in buffer = 557
DCS dac update: bytes in buffer = 449
DCS dac update: bytes in buffer = 342
DCS dac update: bytes in buffer = 475
DCS dac update: bytes in buffer = 368
DCS dac update: bytes in buffer = 500
DCS dac update: bytes in buffer = 393
```

i noticed that during the periods of distortion, the bytes used by the buffer, reported by https://github.com/libretro/mame2003-libretro/blob/master/src/sndhrdw/dcs.c#L915, are close to the defined DCS_BUFFER_SIZE of 4096 (https://github.com/libretro/mame2003-libretro/blob/master/src/sndhrdw/dcs.c#L23). the distortion goes away as it begins to go over 4096 bytes, and then will start up again as it reaches 8192, etc.

if you raise DCS_BUFFER_SIZE to 8192, it takes longer for the issues to start, but it still has the same problem, as the bytes in the buffer will continue to rise forever.

i don't know ANYTHING about audio programming, but i would have thought the buffer size should act as a limit, which cannot be exceeded? it seems this is quite happy to go above the buffer :) i want to try and preempt this behavior and reset the buffer before it reaches of DCS_BUFFER_SIZE, but i'm not sure if this is the right approach, or how to do it.

PS, if you want to quickly recreate this, just set DCS_BUFFER_SIZE to 1024 or something lower, and it will start happening in a few minutes.

**Comment by dankcushions** [comment]
I tried this with the standalone version of mame 0.78 on windows, and it worked fine. I can only presume something about the libretro changes, or the way it is being compiled, is causing this. it's strange it only affects these DCS games, though!

i may get a windows dev environment set up to see if i can spot any differences when debugging, but not sure when i'll get around to that.

PS You can download old versions of the windows binary and source here: https://mirrors.xmission.com/mame/releases

**Comment by dankcushions** [comment]
I've recreated this issue in this libretro core in windows, so it's definitely a libretro-related issue (or at least, something that changed during the port)

**Comment by dukesilverfan** [comment]
Is there anything I can do to help gather information on this issue. I think you are on to something here with the buffer size. Have you tested this on a game without a known issue, such as MK1, to see if the buffer behaves correctly there?

**Comment by vince-geekcore** [comment]
Just want to say that i encounter the same issue on mame2003 (latest retropie script) with an intel atom based PC running Ubuntu. Hope we can find a way to fix this.. would love to have an arcade perfect MK series.

**Comment by dankcushions** [comment]
I've posted a $15 bounty for this: https://www.bountysource.com/issues/36272753-dcs-games-mk2-etc-slowly-overflow-the-buffer-periodically-distorting-sound

$15 is a bit arbitrary. it SHOULD be a minor fix as it works fine in standalone, but finding the fix is the tricky party :)

**Comment by dankcushions** [comment]
@vince-geekcore has now raised it to $25 👍

**Comment by dankcushions** [comment]
Bounty raised to $50 - thanks @dukesilverfan (I think?) :dagger: 

Ok, had another look at this. I think I might have some clues. The core audio stream code in the original Mame 0.78 (standalone) was changed quite a bit:
```
**Original code:**
/*
  osd_start_audio_stream() is called at the start of the emulation to initialize
  the output stream, then osd_update_audio_stream() is called every frame to
  feed new data. osd_stop_audio_stream() is called when the emulation is stopped.

  The sample rate is fixed at Machine->sample_rate. Samples are 16-bit, signed.
  When the stream is stereo, left and right samples are alternated in the
  stream.

  osd_start_audio_stream() and osd_update_audio_stream() must return the number
  of samples (or couples of samples, when using stereo) required for next frame.
  This will be around Machine->sample_rate / Machine->drv->frames_per_second,
  the code may adjust it by SMALL AMOUNTS to keep timing accurate and to
  maintain audio and video in sync when using vsync. Note that sound emulation,
  especially when DACs are involved, greatly depends on the number of samples
  per frame to be roughly constant, so the returned value must always stay close
  to the reference value of Machine->sample_rate / Machine->drv->frames_per_second.
  Of course that value is not necessarily an integer so at least a +/- 1
  adjustment is necessary to avoid drifting over time.
*/

```
```
int osd_update_audio_stream(INT16 *buffer)
{
	// if nothing to do, don't do it
	if (Machine->sample_rate != 0 && stream_buffer)
	{
		int original_bytes = bytes_in_stream_buffer();
		int input_bytes = samples_this_frame * stream_format.nBlockAlign;
		int final_bytes;

		// update the sample adjustment
		update_sample_adjustment(original_bytes);

		// copy data into the sound buffer
		copy_sample_data(buffer, input_bytes);

		// check for overflows
		final_bytes = bytes_in_stream_buffer();
		if (final_bytes < original_bytes)
			buffer_overflows++;
	}

	// reset underflow/overflow tracking
	if (++total_frames == INGORE_UNDERFLOW_FRAMES)
		buffer_overflows = buffer_underflows = 0;

	// update underflow/overflow logging
#if (DISPLAY_UNDEROVERFLOW || LOG_SOUND)
{
	static int prev_overflows, prev_underflows;
	if (total_frames > INGORE_UNDERFLOW_FRAMES && (buffer_overflows != prev_overflows || buffer_underflows != prev_underflows))
	{
		prev_overflows = buffer_overflows;
		prev_underflows = buffer_underflows;
#if DISPLAY_UNDEROVERFLOW
		usrintf_showmessage("overflows=%d underflows=%d", buffer_overflows, buffer_underflows);
#endif
#if LOG_SOUND
		fprintf(sound_log, "************************ overflows=%d underflows=%d\n", buffer_overflows, buffer_underflows);
#endif
	}
}
#endif

	// compute how many samples to generate next frame
	samples_left_over += samples_per_frame;
	samples_this_frame = (UINT32)samples_left_over;
	samples_left_over -= (double)samples_this_frame;

	samples_this_frame += current_adjustment;

	// return the samples to play this next frame
	return samples_this_frame;
}
```
***libretro version:***
```
int osd_update_audio_stream(INT16 *buffer)
{
	int i, samplerate_buffer_size;

	samplerate_buffer_size = (Machine->sample_rate / Machine->drv->frames_per_second);

	if (stereo)
		memcpy(XsoundBuffer, buffer, samplerate_buffer_size * 4);
	else
	{
		for (i = 0; i < samplerate_buffer_size; i++)
		{
			XsoundBuffer[i * 2 + 0] = buffer[i];
			XsoundBuffer[i * 2 + 1] = buffer[i];
		}
	}

	return (Machine->sample_rate / Machine->drv->frames_per_second);
}
```

recall that the standalone version works fine.  i think believe the code that is taken out is something that libretro/RA handles itself, but there must be some discrepancy.

**Comment by dukesilverfan** [comment]
Someone with some audio knowledge, please take this money!

**Comment by rtissera** [comment]
Temptative fix in this PR : https://github.com/libretro/mame2003-libretro/pull/98

**Comment by twinaphex** [comment]
Alright, @rtissera has submitted a PR, and it works according to @dankcushions , one of the bounty backers. I am going to close this issue now so that we can proceed to finalizing the bounty; will still need the two other bounty backers to sign off of course.

**Comment by raziel2001au** [comment]
This issue was driving me nuts!!! I'm really glad to see it fixed.
