### ISSUE TITLE
Broke berzerk

### ISSUE THREAD

**Issue by mahoneyt944** [libretro/mame2003-libretro#460]
Just tried back to pre-compiled build 0e8554e. Game loads to black screen and waits. No video. I suspect it might be z80 related? Not sure.

**Comment by Wilstorm** [comment]
@mahoneyt944 - I'm just heading out here but wanted to add real quick it does work in commit f0ea72e using artwork and shaders. I don't see that commit but I updated before the Liberto hack if that changed the numbering?

**Comment by mahoneyt944** [comment]
Now here's the damnedest thing. Just tried on my other pi running 0e8554e and it's working?

**Comment by mahoneyt944** [comment]
Updated working pi from source. Berzerk is fine. So the issue is on my other pi not mame2003

**Comment by mahoneyt944** [comment]
Updating retropie fixed this issue. Not sure what messed up or why. But everything is good now.
