### ISSUE TITLE
Mouse input--not mapping player2

### ISSUE THREAD

**Issue by caver01** [libretro/mame2003-libretro#48]
With recent updates, mouse inputs are now working well. Games with a single axis input appear to be mapped to the X-axis. However, player 2 inputs are not mapped. Several 2 player games would be playable with player 2 mapped to the Y-axis of the mouse input.

**Comment by dankcushions** [comment]
as some background, it seems some (all?) spinner/dial controllers appear as one mouse device to computers. player 1 is the X axis, and player 2 is the Y. right now, this mame core wants one mouse device for each player, and only cares about the X axis for spinners/dials. we need to allow mame to allow one mouse device to be 'shared' in this manner.

I've tried to see if I could get this working in standalone mame 2003/0.78, to see if this is a configuration option i could expose, but no luck. from reading here: http://forum.arcadecontrols.com/index.php?topic=13527.0 - it looks like flipping the mouse axis wasn't possible in this version of mame anyway.

so, i think the only option is to have a new core option that does this bespokely, letting 2 players share 1 mouse "device". i'd like to try and limit it to dial games (as other games use both the X/Y mouse axes for 1 player - eg tracball/lightgun games), but if not it should be set via per-game core options.

**Comment by dankcushions** [comment]
https://github.com/libretro/mame2003-libretro/pull/49
