### ISSUE TITLE
cheat cose cause retroarch freeze and close

### ISSUE THREAD

**Issue by naxil** [libretro/mame2003-libretro#499]
android git= c97bc0d
game=sf2 roms from latest mame merged (14/09/2022)
cheat= choose pl1 vega on player selection screen
internal cheat mame menu set cause freeze and close retroarch

**Comment by mahoneyt944** [comment]
Cheats are an add on which can sometimes cause undefined results. I don't think there's much that can be done about this besides not using a cheat which is deemed "bad".
