### ISSUE TITLE
Does not compile

### ISSUE THREAD

**Issue by currentyuan** [libretro/mame2003-libretro#5]
Hi.
compile environment：
1.linux:               Ubuntu 11.04(64 bit)
2.ndk version：        android-ndk-r10
3.libretro-super version：           SHA:0b0414521ae63dea2b877bd826b89c81319ad804   link:https://github.com/libretro/libretro-super/tree/0b0414521ae63dea2b877bd826b89c81319ad804(down in 10/21 2014 )
4.mame2003-libretro version:         SHA:5705b927c60586668f51aff82ead0112cdbce71a    link:https://github.com/libretro/mame2003-libretro/tree/5705b927c60586668f51aff82ead0112cdbce71a

mame2003 problems：
question 1: compile: ./libretro-build-android-mk.sh    there are many files not found  as:src/vidhrdw/truco.c;src/machine/gaelco2.c.......
question 2: find the files and modify the filename. libretro-super/libretro-mame078/src/libretro/jni/Android.mk   as:src/vidhrdw/truco_vidhrdw.c;src/machine/gaelco2_machine.c......
            at this step, compile and link ok,but it crashed when running this core after showing the copyright. Attatched the crash log.
Please help me to check this problem.
Thanks!

**Comment by markwkidd** [comment]
@currentyuan I believe this has been fixed now. Can you confirm?
