### ISSUE TITLE
Artwork support

### ISSUE THREAD

**Issue by dankcushions** [libretro/mame2003-libretro#50]
I've attempted implementing this on a branch (link to come), but when turned on the image was corrupted - all green and distorted. not sure why, but flagging this as an issue so I can come back to it.

**Comment by markwkidd** [comment]
What do you mean by artwork? Any chance you are referring to thumbnails and my work on that topic would be useful? MAME thumbnails: https://github.com/libretro/libretro-thumbnails/pull/80

**Comment by dankcushions** [comment]
mame artwork is the background/surround images used in some cabinets. eg the static painted image used in some vector games

http://mrdo.mameworld.info/mame_artwork/invaddlx.png

so it's different, yeah :)

**Comment by Darknior** [comment]
Woaw if you can do it one it will be fantastic :)

**Comment by UDb23** [comment]
Libretro Overlay artwork is supported. Mame artwork supports also backdrop (Libretro does not) but only in the old .art mame format. This old format has issues in correctly setting artwork.
LAY format was introduced with Mame versions after .106 adn works great. 

Could .LAY support be backported to lr-Mame2003 ? 

Mame2010 does support it but it's way too slow on a Pi3 if you enable artwork. Even Space Invaders becomes too slow with full bezel and backdrop.

**Comment by rb6502** [comment]
.LAY was implemented after 0.106 because it relies on GPU compositing, which to backport would require backporting the entire 0.106 new video system, at which point the core wouldn't run on any of the potatoes you guys seem to target.  So I'd close this as unrealistic :)

**Comment by dankcushions** [comment]
@rb6502 this core predates .lay so that was never on the table, and performance is not the issue with the artwork in .78

**Comment by rb6502** [comment]
I was directly replying to @UDb23's question about backporting .LAY.

As far as performance, "it's way too slow on a Pi3 if you enable artwork" sounds like performance is an issue.  IIRC you can fix it on pre-0.106 by running the lowest output resolution you can stand; this is why we switched to GPU compositing :)

**Comment by dankcushions** [comment]
you said to close this issue as unrealistic - udb23’s comment does not reflect the issue.

and the performance problem was staged as is with artwork and mame2010 (which is post .106), not this core, which is mame2003 (pre .106).

**Comment by UDb23** [comment]
Personally what I'd like in particular is backdrop support in lr-mame2003.
Libretro does not support it; only overlays "on top" of actual game.
Mame .art files should allow this but it seems .art support it is not working correctly in lr-mame2003.

**Comment by markwkidd** [comment]
This should be resolved in the latest build :)
