### ISSUE TITLE
Bally MCR Games, can't add credits.

### ISSUE THREAD

**Issue by dabonetn** [libretro/mame2003-libretro#55]
Trying Tapper and Satan's Hollow, the games start but I can't add credits.

**Comment by bengus64** [comment]
I have similar issues with a lot of early Bally/Miday MCR  games as well. One workaround I have found, and this only works with certain titles is to set them to launch with lr-mame2010 from the runcommand menu. This only works for certain titles, but I can confirm you will be able to insert credits for some of the aforementioned. We should really compile a list of specific titles that have this issue. Want to do that with me?

**Comment by dabonetn** [comment]
Here are the standard MCR games.

      A. Kick/Kickman
      B. Tron
      C. Satan's Hollow
      D. Tapper
      E. Timber
      F. Discs of Tron
      G. Spy Hunter
      H. Solar Fox
      I. Two Tigers
      J. Journey
      K. NFL
      L. Wacko
      M. Demolition Derby
      N. Sarge
      O. Kozmik Krooz'r

I haven't tested any of the others, but all these use the same hardware.

**Comment by dabonetn** [comment]
Ok, I tested all but NFL, and currently none work.

Kick/Kickman
Mirror image / turned on side / runs / no input

Tron
runs / no input

Satan's Hollow
runs / no input

Tapper
runs / no input

Timber
Blank screen with the mame volume setting displayed

Discs of Tron
Comes up with the Palette display

Spy Hunter
Blank screen with the mame volume setting displayed

Solar Fox
Mirror image / turned on side / no input
Then resets to blank screen, running the rom again gets into test mode with no input

Two Tigers
runs / no input

Journey
runs / no input

Wacko
runs / no input

Demolition Derby
Blank screen with the mame volume setting displayed

Sarge
Blank screen with the mame volume setting displayed

Kozmik Krooz'r
runs / no input

**Comment by Laddyacris** [comment]
Hello
star wars 
runs / no input

**Comment by rementis** [comment]
Any hope for a fix?  The game plays in lr-mame2010, but the screen is too wide and makes the game look terrible.

**Comment by Vidi0t** [comment]
We can add Domino Man to the list of games that will not take credits. Does anyone know if there will be further development of mame2003-libretro? I'm really hoping they will add artwork support and fix this insert coin issue. Anyone know how to message the people who work on it to send them suggestions?

**Comment by dankcushions** [comment]
@Vidi0t mame2003 is a port of mame as it was in 2003. anything that is a problem in the original mame code probably won't be fixed as it's surely fixed in current mame: https://github.com/mamedev/mame - the only use-case for this old mame core is on old/low-power devices.

if it's an issue with just this libretro port then logging an issue on git is enough. anyone who's interested in fixing things watches the issues.

i had a quick look but couldn't see anything obvious that was wrong with the input bindings. the next step would be to test it works in standalone mame 0.78.

**Comment by blinkydoos** [comment]
I tested a bunch of Bally games on MAME 0.78 (Windows) and they all work fine, you can add credits and all controls work. https://github.com/libretro/mame2003-libretro/issues/121#issuecomment-330029410

**Comment by grant2258** [comment]
I think we can close this one too it's fixed

**Comment by hizzlekizzle** [comment]
closing. feel free to open it back up if the problem persists
