### ISSUE TITLE
Enable mouse in lr-mame2003

### ISSUE THREAD

**Issue by Fourmi** [libretro/mame2003-libretro#66]
How to enable mouse in lr-mame2003 to play Arkanoid ?
i try many thing but no issue .... (retroarch.cfg,etc...)
thx

**Comment by dankcushions** [comment]
Do you see 'Mouse Device' in core options? It should be set to 'Mouse'

I haven't tested with Arkanoid so can you test with centipede, which I know works?

Your mouse will need to be seen by retroarch as a mouse, so more info of your OS and setup is needed.
