### ISSUE TITLE
PS Vita Mame Menu

### ISSUE THREAD

**Issue by nubecitas** [libretro/mame2003-libretro#67]
The R2 button don't exists on PS Vita, in the Mame Cores of PS Vita, the default button for MAME Menu is R2, I think it can be redefined by default to R1+L1, currently is not way to access to Dip Switches and Cheat menu.

**Comment by dankcushions** [comment]
i don't really like having it on any buttons as it means you can't bind R2 (button 8) to anything, or you hit hit by accident. I think the best solution would be to trigger it via holding a button (or combo of buttons) like lr-fbalpha does: https://github.com/libretro/fbalpha/commit/05b6e6c91a13095dce9c1fa4d36e76635c9fc101

**Comment by nubecitas** [comment]
Currently is binded to R2, i propose R1+L1 combo, on PSVita R2 button don't exists.

**Comment by dankcushions** [comment]
like i said, any combos will be hit by accident especially in fighting games. the correct solution is to hold a button (or combo) down like fbalpha does in the linked commit. you could choose whatever button/combo you wanted.

**Comment by nubecitas** [comment]
Yep, holding R1+L1 for some seconds is a good idea, the problem is, retroarch don't have a button for mame menú, is stored in the core by default in R2, Mame don't have option for action holding buttons, only works with combos, i think is better R1+L1+Select+Start or something like this, than the current R2, R2 don't exists in PS Vita. R1+L1+Select+Start is better solution, you never hit this combination in a game, and the developers dont need to modify the mame code for support hold buttons, only need to change the default R2 button, this button dont exists in PS Vita, and you cannot access to this menu for chage Switches, Cheats etc...

**Comment by Laddyacris** [comment]
On PS Vita, I choose user 1 button 8> R button 
in game, hold R button to access Mame Menu

**Comment by hizzlekizzle** [comment]
closing. feel free to open it back up if the problem persists
