### ISSUE TITLE
Extra key combinations for F2/TAB (Service and Config)

### ISSUE THREAD

**Issue by Vapulabe** [libretro/mame2003-libretro#71]
It'd be great if the Service Button and the MAME Menu button (F2 and Tab) could be mapped to SELECT+... sequences (SELECT + A,SELECT + Y, SELECT+DOWN, SELECT+UP SELECT + Right Trigger, SELECT + Left Trigger still available).

It'd allow to call these from a gamepad controller and/or a  Raspberry Pi cabinet without having to connect a keyboard.

**Comment by markwkidd** [comment]
as of the latest builds of mame2003-plus, you can get into the MAME menu (what some call the Tab menu) by launching the RetroArch quick menu and toggling a core option.

there is not such a straightforward way to trigger F2 without mapping a key to it, however.

**Comment by dankcushions** [comment]
this is a good interim, but for me a better solution is to allow configurable hotkey combos like @Vapulabe suggests. fbalpha allows this: https://github.com/libretro/fbalpha/blob/master/src/burner/libretro/libretro.cpp#L181

however... trickier to implement.

**Comment by markwkidd** [comment]
With the latest build of MAME 2003, you can now turn off and on the MAME menu from a core option as in MAME 2003-Plus.

Incremental improvement 🐢

**Comment by mahoneyt944** [comment]
These can be set under "input general"
