### ISSUE TITLE
Fails to open roms from command line without full path

### ISSUE THREAD

**Issue by orbea** [libretro/mame2003-libretro#74]
OS: `Slackware64-current`
`RetroArch-2017.01.03_faf939856_master-x86_64-1_git`
`mame2003-libretro-2016.12.10_6fcd8cd_master-x86_64-1_git`

mame2003-libretro fails to open roms from the command line if a full path is not specified.

Works:
* `retroarch -L /usr/lib64/libretro/mame2003_libretro.so ./pacman.zip`
* `retroarch -L /usr/lib64/libretro/mame2003_libretro.so roms/pacman.zip`
* Starting the game from the menu.

Fails:
* `retroarch -L /usr/lib64/libretro/mame2003_libretro.so pacman.zip`
```
pacman.6e    NOT FOUND
pacman.6f    NOT FOUND
pacman.6h    NOT FOUND
pacman.6j    NOT FOUND
pacman.5e    NOT FOUND
pacman.5f    NOT FOUND
82s123.7f    NOT FOUND
82s126.4a    NOT FOUND
82s126.1m    NOT FOUND
82s126.3m    NOT FOUND
ERROR: required files are missing, the game cannot be run.
```
This does work in mame2000-libretro.

I suspect this has to do with something around here, but I'm not quite sure what do about it...
https://github.com/libretro/mame2003-libretro/blob/master/src/libretro/libretro.c#L525

**Comment by dankcushions** [comment]
where is pacman.zip in this context? in the defined content_dir? or current directory?

**Comment by orbea** [comment]
Current directory.

**Comment by markwkidd** [comment]
now fixed in mame2003-plus. coming eventually to mame2003!

**Comment by markwkidd** [comment]
This is fixed as of today. Slow and steady!
