### ISSUE TITLE
Refresh Rates Wrong on some games ?

### ISSUE THREAD

**Issue by windale** [libretro/mame2003-libretro#75]
I noticed it on playing the game Robocop in Mame2003. The game plays slightly too fast. I turned on the FPS in the RetroArch menu and when sitting in the menu the Refresh Rate is reported correctly at 57.4 (for Robocop). When exiting the RetroArch menu and playing the game it goes up to 60 fps again which is too fast. I'm assuming this happens on all mame2003 games (that aren't 60Hz). Tested on Raspberry Pi 3.

**Comment by dankcushions** [comment]
hmm, do you have vsync on? if vsync is on i believe it would have to run at factors of the display modes refresh rate (probably 60hz). so 60, 30, 20, 15, etc. 

(in that case i guess the bug would be that it reports 57.4 at the start)

**Comment by hizzlekizzle** [comment]
Frame-throttling for the menu is not always the same as in-game, which could explain the initial refresh rate, but yeah, if you have vsync enabled, it will run the game faster to match the monitor's refresh rate and resample the audio accordingly. To leave the refresh rate untouched, disable vsync and use audio sync instead.

**Comment by windale** [comment]
VSync is ON. I tried two more games, Mortal Kombat (54.7 Hz) and R-Type (55 Hz) and they both report the correct FPS in-game. 

I decided to try some more Data East games.

Bad Dudes vs Dragon Ninja (57.4 Hz)
Midnight Resistance (57.4 Hz)
Burger Time (57.4 Hz)
Caveman Ninja (58 Hz)

All these games play at 60 Hz in-game which is slightly too fast. Is it something to do with the Data East drivers or maybe other games also play at the wrong Hz ?

**Comment by hizzlekizzle** [comment]
I think it has to do with the max timing skew setting. Once the timing difference reaches that threshold, RetroArch gives up and just runs it at whatever speed. So, an alternative to disabling vsync could be to just reduce the max timing skew until 57.4/58 hz is outside of the range. Then, it will still skew the timing on games that are very close (think NTSC timing) but not do it for those other games.

**Comment by windale** [comment]
Not at home at the moment but before I went out I tried turning OFF VSync in the RetroArch menu but it didn't make any difference.

**Comment by dankcushions** [comment]
if vsync off doesn't fix it it seems like it must be a RA/libretro issue because those games are setting the refresh rate to these numbers using the API. i need to test to confirm the core isn't doing anything daft!

**Comment by TheLazyFloyd** [comment]
I want to report this bug too, and I posted about it here at retropie forums:
https://retropie.org.uk/forum/topic/7502/mame-emulation-speed-faster-on-retropie-than-on-my-pc/

The game in question is Super Pang (CP1 system) and I experience the same problems as the OP. Game runs faster around 10%. Adding video_frame_delay does help out with the issue but still doesn't fix problems. Adding delay is never a good solution.
I experience this only in RetroPie and not PC. Vsync off isn't helping either.

**Comment by TheLazyFloyd** [comment]
I found a fix : 
I'm quoting my text which I wrote on retropie forum (link above)

> I think I've found a fix.
> Here is the solution. As it seems, retroarch isn't detecting mame refresh rate properly and instead it automatically forces it to 60hz. Now to fix this, you just need to go to Select + X to call the Retroarch menu and undeo Settings > Video  scroll to Refresh rate. It defaults to 60.0000 Hz. Now change that value to game's proper refresh rate (which you can find by running the game in mame on your pc and reading the values right before the game starts). 
> After changing the refresh rate, in my case Super Pang had a refresh rate of 57.420 save that setting (Overide per game). The setting should be saved in /home/pi/.config/config/mame-2003/spang.txt
> Little hint, it takes a long time to change the refresh rate via gamepad in RetroArch Gui. Instead just save it before changing the value and it will create the gamename.txt file. There you can open it (via putty) or file explorer and edit the value. Look for "refresh_rate" and change from 60.00000 to your desired refresh rate.
> That should do the trick and the game should run at normal speed

**Comment by windale** [comment]
@Floyd This is more of a workaround than a fix. This means we will have to keep an eye on the framerate of every game we play and check if it's correct with the Windows etc. version of MAME and then manually edit the refresh rate for all of them ! I hope there is an easier solution, maybe a bug in RetroArch. I don't know if @dankcushions is looking into it ?

**Comment by windale** [comment]
@hizzlekizzle So does this work for all games that play at the wrong refresh rate (including the ones listed above) ? Can this be set globally as I don't see any reason for fast-forward on MAME ?

**Comment by hizzlekizzle** [comment]
@windale I haven't tested all of them, but I just tried baddudes with that setup and it locked in at 57.4, so yeah, seems to be reliable. And yeah, I think it should be fine to set a core override with those settings, as loss of FF should be the only problem caused by it.

**Comment by dankcushions** [comment]
@hizzlekizzle i wonder if this is a problem with the core or the api/retroarch? i think it must be the latter as the core is setting the 57 frame rate in the menu at least. 

does the run speed workaround work with even vsync on?

(sorry, away from my pi and can't test myself!)

**Comment by windale** [comment]
I just tested the 'Maximum Run Speed to 1.0x', it fixes the correct refresh rate but unfortunately makes the audio crackle.

**Comment by hizzlekizzle** [comment]
Hmm, audio sounds fine here.

@dankcushions It would be a RetroArch issue, I think.

**Comment by windale** [comment]
@hizzlekizzle To be honest, I only had time to test one game before I went out, RoboCop. Could you try it please ? I had crackling audio.

**Comment by hizzlekizzle** [comment]
Just tried it and it sounds okay here.

**Comment by windale** [comment]
I tested all the games I listed in this thread (with max speed 1.0x) and they all have dodgy audio pops and crackle. I am using a Raspberry Pi 3. Maybe this doesn't have the power to keep it synced ? Are you using a more powerful device ?

**Comment by hizzlekizzle** [comment]
Yeah, this was on my sandy bridge i7 laptop.

**Comment by dankcushions** [comment]
@hizzlekizzle @windale 
i get the crackle here also. i tried it on my pi3 and my macbook air. the latter wasn't under load. i think it's a bit subtle on baddudes - i can't really hear the skipping audio until synthy parts later on in the level.

i've got a fix to make the mitchell (pang) driver to be the correct framerate but i guess not much point in it until we've worked out the retroarch problem!

**Comment by dankcushions** [comment]
I logged it to RetroArch: https://github.com/libretro/RetroArch/issues/4662

**Comment by dankcushions** [comment]
ok, follow discussion in https://github.com/libretro/RetroArch/issues/4662 @Monroe88 discovered the problem. it's the mentioned audio_max_timing_skew setting. it resamples game audio so games that are close to 60hz can be 60hz. it's just perhaps the default value of 'close to' is too aggressive. we can change it with your input.

set `audio_max_timing_skew = 0.02` (it is in audio settings). this should make the correct frame rate in game. you can have v sync on or off. audio should be correct regardless. v sync on should dupe the occasional frame (?). 

if this fixes the issue for you then we can propose 0.02 as new default. 

btw this only works in games that were displaying the correct frame rate in the menu - my fix for pang etc will be the next step.

**Comment by dankcushions** [comment]
i see @hizzlekizzle pretty much said the same thing earlier :) sorry about that!

**Comment by windale** [comment]
So I tried Robocop as the test subject, put the FPS display ON and set 'audio_max_timing_skew = 0.02'. I entered gameplay and the FPS goes back up to 60 Hz !?! I tried Vsync On and Off (in RetroArch Menu) and no difference. How did you achieve this fix ? (My TV is set to 1080p60).

**Comment by dankcushions** [comment]
@windale 
i just tried again and it looks like you need to save it in a config and restart the core/game for it to take effect. 57.4 for me. with vsync on i can see the hitch about once a second, which makes sense. with v sync off it seemed the same. pass... i guess the audio should be better, at least?

> EDIT: I set 'Maximum Run Speed to 1.0x' but I can still hear crackle.

turn this back to default (0x?) for this test please

**Comment by windale** [comment]
Yes, saving the config works. The slight video stutter is obviously unavoidable due to the strange refresh rates of lots of arcade games, it also happens on the PC versions of MAME.

**Comment by dankcushions** [comment]
great! ok, so are we all in agreement that the stutter is better than the (slightly) incorrect framerate and audio? so i should create a fix for Retroarch that defaults 
`audio_max_timing_skew = 0.02`
that would handle our cases, but not affect very subtle frame rate variations that are used in other systems?

also, if anyone could give me any games were the framerate is wrong even with this fix, I can make the appropriate driver changes. right now i have one ready to go for pang/super pang and a bunch of other mitchell games.

**Comment by windale** [comment]
The refresh rate for Super Pang wasn't corrected until the MAME Team changed it in v0.133. At the time they thought 60Hz was correct in MAME 0.78. This means that there are probably a lot of games since MAME 0.78 that have had there refresh rates corrected but they would have to be checked manually with the latest MAME version.

**Comment by dankcushions** [comment]
ok, i've done a comparison between mame 0.78 and 0.182 (current) refresh rates via some excel-fu. If i filter by differences greater than 2, there's 158. i will go through these and submit those that i am familiar with/can test first.

still could do with some input on whether we should propose the default audio_max_timing_skew in retroarch is changed from 0.05 to 0.02 (or other)

**Comment by hizzlekizzle** [comment]
If 0.02 catches all of them, I'm okay with it. However, I think it's arguable whether the "average" user prefers running at the wrong speed with smooth scrolling, working transparency effects, etc. or the correct speed with stuttery video, blinkie transparency effects, etc.

As long as one can set it to 0.02 or whatever from the menu, I'm not sure if it needs to be the default behavior.

**Comment by dankcushions** [comment]
@hizzlekizzle i agree. for me if it's a stones throw from 60hz, i want smooth 60hz. i've played pang on mame2003 a lot and i remember it well as a child, and i'd not noticed the fact that it was 2.6fps too fast :)

**Comment by windale** [comment]
Yes, but there are some games that use their own correct refresh rate without using this fix

Mortal Kombat (54.7 Hz)
R-Type (55 Hz) etc.

Why are they using the correct refresh and others aren't. Either way not all games are going to play at smooth 60Hz whether you use this fix or not.

**Comment by dankcushions** [comment]
> Yes, but there are some games that use their own correct refresh rate without using this fix
> 
> Mortal Kombat (54.7 Hz)
> R-Type (55 Hz) etc.
> 
> Why are they using the correct refresh and others aren't

because these don't fall within the `audio_max_timing_skew` default of 0.05. using the existing default, if a game is 57Hz or above then it would fall within that threshold, and run at 60Hz and get the audio resampled to same. anything below that (or above 63Hz) plays at whatever framerate it should.

there's an example of the calculation here: https://github.com/libretro/RetroArch/issues/4662#issuecomment-280871837

**Comment by dankcushions** [comment]
ok, following https://github.com/libretro/mame2003-libretro/issues/82 i have backported a few refresh rate corrections from current mame to 0.78 drivers/games i'm familiar with. i have an excel spreadsheet that compares current to 0.78 if anyone wants to have a look at some others.

i think the default for audio_max_timing_skew should stay as it is, so i guess this is solved?

**Comment by windale** [comment]
So you haven't changed any of the games listed in this thread ? You've only changed Pang (which is supposed to be 60Hz in MAME 0.78 anyway) and a couple of others ?

**Comment by dankcushions** [comment]
@windale the other games listed already had the correct refresh rates in this core, but to see them you will need to set audio_max_timing_skew as discussed. i have backported the corrected current mame refresh rates to pang (and super pang, mentioned in this thread) and a couple of other drivers here.
