### ISSUE TITLE
Hiscore.dat doesn't seem to work in NES Classic.

### ISSUE THREAD

**Issue by Hackcell** [libretro/mame2003-libretro#87]
I've uploaded the hiscore.dat file to etc\libretro\system\mame2003\hi, nevertheless mame2003 (running in a NES classic) doesn't save any high scores.

Am I placing the file in the wrong location?

**Comment by dankcushions** [comment]
it should be in /mame2003/ in your system directory (wherever you've configured that in retroarch). for you it probably needs to be moved of that /hi/ directory. 

The readme says this btw :)

**Comment by Hackcell** [comment]
Thanks for the heads up. I'll give a try later today!

**Comment by Hackcell** [comment]
Thanks for the heads up. I'll give a try later today.
