### ISSUE TITLE
mame nag message on every load + needs keyboard

### ISSUE THREAD

**Issue by objectchris** [libretro/mame2003-libretro#9]
the generic mame 'nag' message appears when you load every rom. This might be just generic to mame emulators (although not for every one I've tried), but currently it won't let you move on until you type "ok" on the keyboard. I don't want a keyboard plugged into my emulation system! :)

**Comment by fr500** [comment]
I think you can move forward by pressing left-right

**Comment by objectchris** [comment]
that works! great! it'd be cool if the message also gave that instruction, though.

**Comment by objectchris** [comment]
https://github.com/objectchris/mame2003-libretro/commit/f477fba44bd4c4e57354454c097aad75f7d9077a resolves the message, if merged.

I could suppress the nag screen entirely, or is that bad form? I figure that since this is an old version of mame it should be ok to remove it here, as long as it is kept in the version forked from the latest? https://github.com/libretro/mame

**Comment by objectchris** [comment]
https://github.com/libretro/mame2003-libretro/commit/4145a3bdce45467dcdc9f1bf01aa643e5d4a94c4 adds ability to suppress the nag screen also. can close :)
